In [1]:
import pandas as pd

In [2]:
path = "IJ-118/"
file_ = "IJ-044.csv"
data_final_manutencao = "2024-05-26"

In [3]:
path = "IJ-118/"

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# Read the CSV file into a DataFrame
df = pd.read_csv(path + file_)

In [4]:
# Display the first 5 rows
print(df.head().to_markdown(index=False, numalign="left", stralign="left"))

# Print the column names and their data types
print(df.info())

| Data de Produção   | Cód. Ordem   | Cód. Recurso   | Cód. Produto   | Qtd. Produzida   | Qtd. Refugada   | Qtd. Retrabalhada   | Fator Un.   | Cód. Un.   | Descrição da massa (Composto)   | Consumo de massa no item em (Kg/100pçs)   |
|:-------------------|:-------------|:---------------|:---------------|:-----------------|:----------------|:--------------------|:------------|:-----------|:--------------------------------|:------------------------------------------|
| 2023-08-21         | 2680830      | IJ-044         | SA08395        | 239              | 4               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     |
| 2023-08-21         | 2680830      | IJ-044         | SA08395        | 158              | 6               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     |
| 2023-08-21         | 2680830      | IJ-044         | SA08395        | 471              | 11              | 0                   | 1           | PC         | N-142/67                        | 2.869                                     |
| 2023-08-22         | 2680830      | IJ-044         | SA08395        | 479              | 3               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     |
| 2023-08-22         | 2680830      | IJ-044         | SA08395        | 97               | 3               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     |
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Data de Produção                         610 non-null    object
 1   Cód. Ordem                               610 non-null    int64
 2   Cód. Recurso                             610 non-null    object
 3   Cód. Produto                             610 non-null    object
 4   Qtd. Produzida                           610 non-null    int64
 5   Qtd. Refugada                            610 non-null    int64
 6   Qtd. Retrabalhada                        610 non-null    int64
 7   Fator Un.                                610 non-null    int64
 8   Cód. Un.                                 610 non-null    object
 9   Descrição da massa (Composto)            610 non-null    object
 10  Consumo de massa no item em (Kg/100pçs)  610 non-null    float64
dtypes: float64(1), int64(5), object(5)
memory usage: 52.5+ KB
None

In [5]:
# Convert `Data de Produção` to datetime
df["Data de Produção"] = pd.to_datetime(df["Data de Produção"])

# Calculate the days until '2024-05-26'
df["Manutencao"] = (
    pd.to_datetime(data_final_manutencao) - df["Data de Produção"]
).dt.days

# Drop the original `Data de Produção` column
df = df.drop("Data de Produção", axis=1)

# Rename `Remaining Days` to `Data de Produção`
# df = df.rename(columns={"Remaining Days": "Data de Produção"})

# Display the first 5 rows
print(df.head().to_markdown(index=False, numalign="left", stralign="left"))

# Print the column names and their data types
print(df.info())

| Cód. Ordem   | Cód. Recurso   | Cód. Produto   | Qtd. Produzida   | Qtd. Refugada   | Qtd. Retrabalhada   | Fator Un.   | Cód. Un.   | Descrição da massa (Composto)   | Consumo de massa no item em (Kg/100pçs)   | Manutencao   |
|:-------------|:---------------|:---------------|:-----------------|:----------------|:--------------------|:------------|:-----------|:--------------------------------|:------------------------------------------|:-------------|
| 2680830      | IJ-044         | SA08395        | 239              | 4               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 279          |
| 2680830      | IJ-044         | SA08395        | 158              | 6               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 279          |
| 2680830      | IJ-044         | SA08395        | 471              | 11              | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 279          |
| 2680830      | IJ-044         | SA08395        | 479              | 3               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 278          |
| 2680830      | IJ-044         | SA08395        | 97               | 3               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 278          |
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cód. Ordem                               610 non-null    int64
 1   Cód. Recurso                             610 non-null    object
 2   Cód. Produto                             610 non-null    object
 3   Qtd. Produzida                           610 non-null    int64
 4   Qtd. Refugada                            610 non-null    int64
 5   Qtd. Retrabalhada                        610 non-null    int64
 6   Fator Un.                                610 non-null    int64
 7   Cód. Un.                                 610 non-null    object
 8   Descrição da massa (Composto)            610 non-null    object
 9   Consumo de massa no item em (Kg/100pçs)  610 non-null    float64
 10  Manutencao                               610 non-null    int64
dtypes: float64(1), int64(6), object(4)
memory usage: 52.5+ KB
None

In [6]:
df

,Cód. Ordem,Cód. Recurso,Cód. Produto,Qtd. Produzida,Qtd. Refugada,Qtd. Retrabalhada,Fator Un.,Cód. Un.,Descrição da massa (Composto),Consumo de massa no item em (Kg/100pçs),Manutencao
0,2680830,IJ-044,SA08395,239,4,0,1,PC,N-142/67,2.869,279
1,2680830,IJ-044,SA08395,158,6,0,1,PC,N-142/67,2.869,279
2,2680830,IJ-044,SA08395,471,11,0,1,PC,N-142/67,2.869,279
3,2680830,IJ-044,SA08395,479,3,0,1,PC,N-142/67,2.869,278
4,2680830,IJ-044,SA08395,97,3,0,1,PC,N-142/67,2.869,278
5,2680830,IJ-044,SA08395,399,4,0,1,PC,N-142/67,2.869,278
6,2681836,IJ-044,SA08400,39,5,0,1,PC,N148/18,0.550,278
7,2680534,IJ-044,SA07321,97,0,0,1,PC,N148/18,1.900,277
8,2680534,IJ-044,SA07321,368,7,0,1,PC,N148/18,1.900,277
9,2681836,IJ-044,SA08400,337,39,0,1,PC,N148/18,0.550,277
10,2680534,IJ-044,SA07321,231,2,0,1,PC,N148/18,1.900,276
11,2680534,IJ-044,SA07321,521,7,0,1,PC,N148/18,1.900,276
12,2680534,IJ-044,SA07321,155,9,0,1,PC,N148/18,1.900,276
13,2680534,IJ-044,SA07321,237,0,0,1,PC,N148/18,1.900,275
14,2680534,IJ-044,SA07321,489,6,0,1,PC,N148/18,1.900,275
15,2680830,IJ-044,SA08395,135,10,0,1,PC,N-142/67,2.869,275
16,2680830,IJ-044,SA08395,39,0,0,1,PC,N-142/67,2.869,275
17,2680830,IJ-044,SA08395,133,0,0,1,PC,N-142/67,2.869,275
18,2680830,IJ-044,SA08395,163,1,0,1,PC,N-142/67,2.869,273
19,2680830,IJ-044,SA08395,89,0,0,1,PC,N-142/67,2.869,272
20,2680830,IJ-044,SA08395,203,3,0,1,PC,N-142/67,2.869,272
21,2682010,IJ-044,SA01801,213,11,0,1,PC,N146/9,1.590,272
22,2682010,IJ-044,SA01801,248,2,0,1,PC,N146/9,1.590,272
23,2680332,IJ-044,SA02941,177,0,0,1,PC,N148/18,3.380,271
24,2680332,IJ-044,SA02941,89,9,0,1,PC,N148/18,3.380,271
25,2682010,IJ-044,SA01801,142,9,0,1,PC,N146/9,1.590,271
26,2682010,IJ-044,SA01801,382,15,0,1,PC,N146/9,1.590,271
27,2680332,IJ-044,SA02941,4,0,0,1,PC,N148/18,3.380,270
28,2680332,IJ-044,SA02941,1,0,0,1,PC,N148/18,3.380,270
29,2680332,IJ-044,SA02941,305,13,0,1,PC,N148/18,3.380,270
30,2680332,IJ-044,SA02941,210,7,0,1,PC,N148/18,3.380,269
31,2680332,IJ-044,SA02941,34,0,0,1,PC,N148/18,3.380,269
32,2680332,IJ-044,SA02941,505,8,0,1,PC,N148/18,3.380,269
33,2680332,IJ-044,SA02941,89,3,0,1,PC,N148/18,3.380,268
34,2680332,IJ-044,SA02941,170,7,0,1,PC,N148/18,3.380,261
35,2680332,IJ-044,SA02941,365,0,0,1,PC,N148/18,3.380,261
36,2680332,IJ-044,SA02941,188,3,0,1,PC,N148/18,3.380,261
37,2680332,IJ-044,SA02941,138,4,0,1,PC,N148/18,3.380,259
38,2680332,IJ-044,SA02941,132,8,0,1,PC,N148/18,3.380,258
39,2680332,IJ-044,SA02941,423,4,0,1,PC,N148/18,3.380,258
40,2680332,IJ-044,SA02941,415,6,0,1,PC,N148/18,3.380,258
41,2680332,IJ-044,SA02941,197,7,0,1,PC,N148/18,3.380,257
42,2680332,IJ-044,SA02941,256,7,0,1,PC,N148/18,3.380,257
43,2680332,IJ-044,SA02941,412,3,0,1,PC,N148/18,3.380,257
44,2680332,IJ-044,SA02941,184,4,0,1,PC,N148/18,3.380,256
45,2680332,IJ-044,SA02941,322,12,0,1,PC,N148/18,3.380,256
46,2680332,IJ-044,SA02941,369,9,0,1,PC,N148/18,3.380,256
47,2680332,IJ-044,SA02941,26,0,0,1,PC,N148/18,3.380,255
48,2680332,IJ-044,SA02941,398,2,0,1,PC,N148/18,3.380,255
49,2680332,IJ-044,SA02941,351,8,0,1,PC,N148/18,3.380,255
50,2680332,IJ-044,SA02941,189,6,0,1,PC,N148/18,3.380,254
51,2680332,IJ-044,SA02941,421,8,0,1,PC,N148/18,3.380,254
52,2680332,IJ-044,SA02941,179,0,0,1,PC,N148/18,3.380,254
53,2680332,IJ-044,SA02941,54,0,0,1,PC,N148/18,3.380,252
54,2683450,IJ-044,SA02941,122,3,0,1,PC,N148/18,3.380,252
55,2683450,IJ-044,SA02941,20,0,0,1,PC,N148/18,3.380,251
56,2683450,IJ-044,SA02941,438,3,0,1,PC,N148/18,3.380,251
57,2683450,IJ-044,SA02941,24,0,0,1,PC,N148/18,3.380,251
58,2683450,IJ-044,SA02941,387,4,0,1,PC,N148/18,3.380,251
59,2683569,IJ-044,11974,198,5,0,1,PC,N-158/3,3.154,251
60,2683569,IJ-044,11974,111,1,0,1,PC,N-158/3,3.154,250
61,2683569,IJ-044,11974,404,5,0,1,PC,N-158/3,3.154,250
62,2683569,IJ-044,11974,243,15,0,1,PC,N-158/3,3.154,250
63,2683569,IJ-044,11974,122,0,0,1,PC,N-158/3,3.154,249
64,2683666,IJ-044,SA07321,196,4,0,1,PC,N148/18,1.900,249
65,2683666,IJ-044,SA07321,28,2,0,1,PC,N148/18,1.900,249
66,2682511,IJ-044,SA04416,248,11,0,1,PC,P212/1,5.043,248
67,2683666,IJ-044,SA07321,142,6,0,1,PC,N148/18,1.900,248
68,2683666,IJ-044,SA07321,108,3,0,1,PC,N148/18,1.900,248
69,2682511,IJ-044,SA04416,56,0,0,1,PC,P212/1,5.043,247
70,2682511,IJ-044,SA04416,184,2,0,1,PC,P212/1,5.043,247
71,2682511,IJ-044,SA04416,75,0,0,1,PC,P212/1,5.043,246
72,2682511,IJ-044,SA04416,168,1,0,1,PC,P212/1,5.043,246
73,2682511,IJ-044,SA04416,25,1,0,1,PC,P212/1,5.043,246
74,2682511,IJ-044,SA04416,42,2,0,1,PC,P212/1,5.043,244
75,2682511,IJ-044,SA04416,255,0,0,1,PC,P212/1,5.043,244
76,2682511,IJ-044,SA04416,293,10,0,1,PC,P212/1,5.043,244
77,2682511,IJ-044,SA04416,148,5,0,1,PC,P212/1,5.043,243
78,2682511,IJ-044,SA04416,261,0,0,1,PC,P212/1,5.043,243
79,2682511,IJ-044,SA04416,205,5,0,1,PC,P212/1,5.043,243
80,2682511,IJ-044,SA04416,152,3,0,1,PC,P212/1,5.043,242
81,2682511,IJ-044,SA04416,255,0,0,1,PC,P212/1,5.043,242
82,2682511,IJ-044,SA04416,297,4,0,1,PC,P212/1,5.043,242
83,2682511,IJ-044,SA04416,152,3,0,1,PC,P212/1,5.043,241
84,2682511,IJ-044,SA04416,307,0,0,1,PC,P212/1,5.043,241
85,2682511,IJ-044,SA04416,325,2,0,1,PC,P212/1,5.043,241
86,2682511,IJ-044,SA04416,137,3,0,1,PC,P212/1,5.043,240
87,2682511,IJ-044,SA04416,272,0,0,1,PC,P212/1,5.043,240
88,2682511,IJ-044,SA04416,265,6,0,1,PC,P212/1,5.043,240
89,2682511,IJ-044,SA04416,93,0,0,1,PC,P212/1,5.043,239
90,2682511,IJ-044,SA04416,79,2,0,1,PC,P212/1,5.043,237
91,2684278,IJ-044,SA11684,97,33,0,1,PC,N148/18,1.250,237
92,2684278,IJ-044,SA11684,375,7,0,1,PC,N148/18,1.250,237
93,2684278,IJ-044,SA11684,73,0,0,1,PC,N148/18,1.250,237
94,2684278,IJ-044,SA11684,2,0,0,1,PC,N148/18,1.250,237
95,2684278,IJ-044,SA11684,37,0,0,1,PC,N148/18,1.250,237
96,2684451,IJ-044,SA02938,126,0,0,1,PC,N-142/67,2.550,236
97,2684451,IJ-044,SA02938,221,0,0,1,PC,N-142/67,2.550,236
98,2684451,IJ-044,SA02938,333,11,0,1,PC,N-142/67,2.550,236
99,2684451,IJ-044,SA02938,22,0,0,1,PC,N-142/67,2.550,236
100,2684451,IJ-044,SA02938,84,0,0,1,PC,N-142/67,2.550,235
101,2684451,IJ-044,SA02938,328,0,0,1,PC,N-142/67,2.550,235
102,2684451,IJ-044,SA02938,245,7,0,1,PC,N-142/67,2.550,235
103,2684451,IJ-044,SA02938,168,3,0,1,PC,N-142/67,2.550,234
104,2684451,IJ-044,SA02938,338,0,0,1,PC,N-142/67,2.550,234
105,2684451,IJ-044,SA02938,178,15,0,1,PC,N-142/67,2.550,234
106,2684451,IJ-044,SA02938,257,0,0,1,PC,N-142/67,2.550,233
107,2684451,IJ-044,SA02938,360,4,0,1,PC,N-142/67,2.550,233
108,2684656,IJ-044,SA00436,92,10,0,1,PC,N-142/67,1.006,233
109,2684656,IJ-044,SA00436,86,12,0,1,PC,N-142/67,1.006,230
110,2684656,IJ-044,SA00436,24,0,0,1,PC,N-142/67,1.006,230
111,2684656,IJ-044,SA00436,274,6,0,1,PC,N-142/67,1.006,230
112,2684656,IJ-044,SA00436,262,16,0,1,PC,N-142/67,1.006,230
113,2684656,IJ-044,SA00436,318,19,0,1,PC,N-142/67,1.006,229
114,2684656,IJ-044,SA00436,59,0,0,1,PC,N-142/67,1.006,229
115,2684656,IJ-044,SA00436,236,0,0,1,PC,N-142/67,1.006,228
116,2684656,IJ-044,SA00436,107,0,0,1,PC,N-142/67,1.006,228
117,2684656,IJ-044,SA00436,214,3,0,1,PC,N-142/67,1.006,226
118,2684656,IJ-044,SA00436,404,0,0,1,PC,N-142/67,1.006,226
119,2684656,IJ-044,SA00436,399,5,0,1,PC,N-142/67,1.006,226
120,2684656,IJ-044,SA00436,34,5,0,1,PC,N-142/67,1.006,224
121,2684451,IJ-044,SA02938,188,0,0,1,PC,N-142/67,2.550,223
122,2684451,IJ-044,SA02938,280,0,0,1,PC,N-142/67,2.550,223
123,2684656,IJ-044,SA00436,127,0,0,1,PC,N-142/67,1.006,223
124,2684656,IJ-044,SA00436,455,10,0,1,PC,N-142/67,1.006,223
125,2684451,IJ-044,SA02938,397,11,0,1,PC,N-142/67,2.550,222
126,2684451,IJ-044,SA02938,79,7,0,1,PC,N-142/67,2.550,222
127,2684451,IJ-044,SA02938,311,0,0,1,PC,N-142/67,2.550,222
128,2684451,IJ-044,SA02938,77,2,0,1,PC,N-142/67,2.550,221
129,2685403,IJ-044,SA08400,60,0,0,1,PC,N148/18,0.550,221
130,2685521,IJ-044,SA05032,182,0,0,1,PC,N148/18,0.792,221
131,2677754,IJ-044,SA18476,41,0,0,1,PC,N-142/67,0.517,220
132,2677754,IJ-044,SA18476,1,0,0,1,PC,N-142/67,0.517,220
133,2685403,IJ-044,SA08400,101,0,0,1,PC,N148/18,0.550,220
134,2685583,IJ-044,SA18476,214,0,0,1,PC,N-142/67,0.517,220
135,2685583,IJ-044,SA18476,261,5,0,1,PC,N-142/67,0.517,220
136,2685583,IJ-044,SA18476,3,0,0,1,PC,N-142/67,0.517,219
137,2685583,IJ-044,SA18476,359,5,0,1,PC,N-142/67,0.517,219
138,2685583,IJ-044,SA18476,29,0,0,1,PC,N-142/67,0.517,219
139,2685610,IJ-044,SA01974,91,4,0,1,PC,N148/18,2.820,219
140,2685610,IJ-044,SA01974,193,7,0,1,PC,N148/18,2.820,219
141,2685610,IJ-044,SA01974,57,8,0,1,PC,N148/18,2.820,217
142,2685610,IJ-044,SA01974,188,0,0,1,PC,N148/18,2.820,216
143,2685610,IJ-044,SA01974,347,0,0,1,PC,N148/18,2.820,216
144,2685610,IJ-044,SA01974,220,11,0,1,PC,N148/18,2.820,216
145,2685610,IJ-044,SA01974,209,3,0,1,PC,N148/18,2.820,215
146,2685610,IJ-044,SA01974,199,0,0,1,PC,N148/18,2.820,215
147,2685610,IJ-044,SA01974,323,11,0,1,PC,N148/18,2.820,215
148,2685610,IJ-044,SA01974,173,0,0,1,PC,N148/18,2.820,214
149,2685610,IJ-044,SA01974,360,0,0,1,PC,N148/18,2.820,214
150,2685610,IJ-044,SA01974,397,1,0,1,PC,N148/18,2.820,214
151,2685803,IJ-044,SA02910,221,6,0,1,PC,N148/18,0.620,213
152,2685803,IJ-044,SA02910,415,8,0,1,PC,N148/18,0.620,213
153,2685803,IJ-044,SA02910,434,8,0,1,PC,N148/18,0.620,213
154,2685767,IJ-044,SA03682,152,6,0,1,PC,N148/18,6.000,212
155,2685767,IJ-044,SA03682,354,0,0,1,PC,N148/18,6.000,212
156,2685767,IJ-044,SA03682,257,13,0,1,PC,N148/18,6.000,212
157,2685767,IJ-044,SA03682,174,2,0,1,PC,N148/18,6.000,209
158,2685767,IJ-044,SA03682,114,0,0,1,PC,N148/18,6.000,209
159,2685767,IJ-044,SA03682,331,9,0,1,PC,N148/18,6.000,209
160,2684451,IJ-044,SA02938,182,3,0,1,PC,N-142/67,2.550,208
161,2684451,IJ-044,SA02938,164,0,0,1,PC,N-142/67,2.550,208
162,2685767,IJ-044,SA03682,99,0,0,1,PC,N148/18,6.000,208
163,2685767,IJ-044,SA03682,355,7,0,1,PC,N148/18,6.000,208
164,2684451,IJ-044,SA02938,242,2,0,1,PC,N-142/67,2.550,207
165,2684451,IJ-044,SA02938,394,0,0,1,PC,N-142/67,2.550,207
166,2684451,IJ-044,SA02938,367,11,0,1,PC,N-142/67,2.550,207
167,2684451,IJ-044,SA02938,14,0,0,1,PC,N-142/67,2.550,207
168,2684451,IJ-044,SA02938,190,6,0,1,PC,N-142/67,2.550,202
169,2684451,IJ-044,SA02938,212,0,0,1,PC,N-142/67,2.550,202
170,2684451,IJ-044,SA02938,0,8,0,1,PC,N-142/67,2.550,201
171,2684451,IJ-044,SA02938,330,0,0,1,PC,N-142/67,2.550,201
172,2684451,IJ-044,SA02938,480,1,0,1,PC,N-142/67,2.550,201
173,2684451,IJ-044,SA02938,62,0,0,1,PC,N-142/67,2.550,200
174,2686201,IJ-044,SA04416,101,14,0,1,PC,P212/1,5.043,200
175,2686201,IJ-044,SA04416,220,0,0,1,PC,P212/1,5.043,200
176,2686201,IJ-044,SA04416,33,0,0,1,PC,P212/1,5.043,200
177,2686201,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,200
178,2686201,IJ-044,SA04416,35,3,0,1,PC,P212/1,5.043,200
179,2686201,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,200
180,2686201,IJ-044,SA04416,22,0,0,1,PC,P212/1,5.043,200
181,2686201,IJ-044,SA04416,144,0,0,1,PC,P212/1,5.043,199
182,2686201,IJ-044,SA04416,256,0,0,1,PC,P212/1,5.043,199
183,2686201,IJ-044,SA04416,233,16,0,1,PC,P212/1,5.043,199
184,2686201,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,198
185,2686201,IJ-044,SA04416,136,3,0,1,PC,P212/1,5.043,198
186,2686201,IJ-044,SA04416,280,0,0,1,PC,P212/1,5.043,198
187,2686201,IJ-044,SA04416,190,12,0,1,PC,P212/1,5.043,198
188,2686201,IJ-044,SA04416,10,0,0,1,PC,P212/1,5.043,198
189,2686201,IJ-044,SA04416,233,13,0,1,PC,P212/1,5.043,197
190,2686201,IJ-044,SA04416,72,0,0,1,PC,P212/1,5.043,197
191,2686201,IJ-044,SA04416,176,1,0,1,PC,P212/1,5.043,197
192,2686201,IJ-044,SA04416,86,7,0,1,PC,P212/1,5.043,196
193,2686201,IJ-044,SA04416,96,0,0,1,PC,P212/1,5.043,195
194,2686201,IJ-044,SA04416,291,0,0,1,PC,P212/1,5.043,195
195,2686201,IJ-044,SA04416,278,8,0,1,PC,P212/1,5.043,195
196,2686201,IJ-044,SA04416,131,3,0,1,PC,P212/1,5.043,194
197,2686201,IJ-044,SA04416,297,0,0,1,PC,P212/1,5.043,194
198,2686201,IJ-044,SA04416,269,2,0,1,PC,P212/1,5.043,194
199,2686201,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,193
200,2686201,IJ-044,SA04416,280,0,0,1,PC,P212/1,5.043,193
201,2686201,IJ-044,SA04416,146,3,0,1,PC,P212/1,5.043,192
202,2686201,IJ-044,SA04416,300,0,0,1,PC,P212/1,5.043,192
203,2686201,IJ-044,SA04416,355,6,0,1,PC,P212/1,5.043,192
204,2686201,IJ-044,SA04416,142,0,0,1,PC,P212/1,5.043,191
205,2686201,IJ-044,SA04416,318,0,0,1,PC,P212/1,5.043,191
206,2686201,IJ-044,SA04416,320,3,0,1,PC,P212/1,5.043,191
207,2686201,IJ-044,SA04416,2,0,0,1,PC,P212/1,5.043,189
208,2686201,IJ-044,SA04416,48,11,0,1,PC,P212/1,5.043,188
209,2686773,IJ-044,SA07337,57,10,0,1,PC,F420/306,8.733,188
210,2686773,IJ-044,SA07337,124,0,0,1,PC,F420/306,8.733,188
211,2686773,IJ-044,SA07337,90,10,0,1,PC,F420/306,8.733,187
212,2686773,IJ-044,SA07337,174,0,0,1,PC,F420/306,8.733,187
213,2686773,IJ-044,SA07337,156,6,0,1,PC,F420/306,8.733,187
214,2686773,IJ-044,SA07337,151,4,0,1,PC,F420/306,8.733,186
215,2686773,IJ-044,SA07337,277,0,0,1,PC,F420/306,8.733,186
216,2686773,IJ-044,SA07337,290,7,0,1,PC,F420/306,8.733,186
217,2686201,IJ-044,SA04416,169,4,0,1,PC,P212/1,5.043,185
218,2686201,IJ-044,SA04416,175,0,0,1,PC,P212/1,5.043,185
219,2686201,IJ-044,SA04416,6,6,0,1,PC,P212/1,5.043,185
220,2686773,IJ-044,SA07337,146,15,0,1,PC,F420/306,8.733,185
221,2686201,IJ-044,SA04416,176,0,0,1,PC,P212/1,5.043,184
222,2686201,IJ-044,SA04416,304,0,0,1,PC,P212/1,5.043,184
223,2686201,IJ-044,SA04416,383,1,0,1,PC,P212/1,5.043,184
224,2686201,IJ-044,SA04416,277,4,0,1,PC,P212/1,5.043,183
225,2686201,IJ-044,SA04416,287,2,0,1,PC,P212/1,5.043,183
226,2686201,IJ-044,SA04416,145,2,0,1,PC,P212/1,5.043,182
227,2686201,IJ-044,SA04416,191,2,0,1,PC,P212/1,5.043,181
228,2686201,IJ-044,SA04416,342,0,0,1,PC,P212/1,5.043,181
229,2686201,IJ-044,SA04416,336,3,0,1,PC,P212/1,5.043,181
230,2686201,IJ-044,SA04416,192,1,0,1,PC,P212/1,5.043,180
231,2686201,IJ-044,SA04416,313,0,0,1,PC,P212/1,5.043,180
232,2686201,IJ-044,SA04416,201,2,0,1,PC,P212/1,5.043,180
233,2686201,IJ-044,SA04416,195,3,0,1,PC,P212/1,5.043,179
234,2686201,IJ-044,SA04416,342,0,0,1,PC,P212/1,5.043,179
235,2686201,IJ-044,SA04416,336,5,0,1,PC,P212/1,5.043,179
236,2686201,IJ-044,SA04416,198,0,0,1,PC,P212/1,5.043,178
237,2686201,IJ-044,SA04416,333,0,0,1,PC,P212/1,5.043,178
238,2686201,IJ-044,SA04416,337,1,0,1,PC,P212/1,5.043,178
239,2686201,IJ-044,SA04416,329,8,0,1,PC,P212/1,5.043,177
240,2687844,IJ-044,SA04417,161,2,0,1,PC,F420/306,8.773,177
241,2687844,IJ-044,SA04417,323,0,0,1,PC,F420/306,8.773,177
242,2687844,IJ-044,SA04417,173,0,0,1,PC,F420/306,8.773,174
243,2687844,IJ-044,SA04417,157,7,0,1,PC,F420/306,8.773,174
244,2687845,IJ-044,SA04416,139,5,0,1,PC,P212/1,5.043,173
245,2687845,IJ-044,SA04416,1243,0,0,1,PC,P212/1,5.043,173
246,2687845,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,172
247,2687845,IJ-044,SA04416,283,0,0,1,PC,P212/1,5.043,172
248,2687845,IJ-044,SA04416,381,3,0,1,PC,P212/1,5.043,172
249,2687845,IJ-044,SA04416,210,0,0,1,PC,P212/1,5.043,171
250,2687845,IJ-044,SA04416,314,0,0,1,PC,P212/1,5.043,171
251,2687845,IJ-044,SA04416,347,4,0,1,PC,P212/1,5.043,171
252,2687845,IJ-044,SA04416,210,1,0,1,PC,P212/1,5.043,170
253,2687845,IJ-044,SA04416,168,0,0,1,PC,P212/1,5.043,170
254,2687845,IJ-044,SA04416,339,3,0,1,PC,P212/1,5.043,170
255,2686826,IJ-044,SA02583,149,1,0,1,PC,F403/32,6.760,168
256,2686826,IJ-044,SA02583,12,0,0,1,PC,F403/32,6.760,167
257,2687845,IJ-044,SA04416,46,0,0,1,PC,P212/1,5.043,167
258,2686826,IJ-044,SA02583,22,0,0,1,PC,F403/32,6.760,166
259,2686826,IJ-044,SA02583,3,0,0,1,PC,F403/32,6.760,165
260,2686826,IJ-044,SA02583,23,0,0,1,PC,F403/32,6.760,165
261,2686826,IJ-044,SA02583,12,0,0,1,PC,F403/32,6.760,164
262,2686826,IJ-044,SA02583,9,0,0,1,PC,F403/32,6.760,164
263,2689104,IJ-044,SA04416,25,20,0,1,PC,P212/1,5.043,163
264,2689104,IJ-044,SA04416,29,0,0,1,PC,P212/1,5.043,163
265,2689104,IJ-044,SA04416,4,0,0,1,PC,P212/1,5.043,163
266,2689104,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,161
267,2689104,IJ-044,SA04416,174,0,0,1,PC,P212/1,5.043,160
268,2689104,IJ-044,SA04416,301,0,0,1,PC,P212/1,5.043,160
269,2689104,IJ-044,SA04416,243,22,0,1,PC,P212/1,5.043,160
270,2689104,IJ-044,SA04416,133,4,0,1,PC,P212/1,5.043,159
271,2689104,IJ-044,SA04416,72,0,0,1,PC,P212/1,5.043,159
272,2689104,IJ-044,SA04416,209,22,0,1,PC,P212/1,5.043,159
273,2689104,IJ-044,SA04416,168,4,0,1,PC,P212/1,5.043,158
274,2689104,IJ-044,SA04416,292,0,0,1,PC,P212/1,5.043,158
275,2689104,IJ-044,SA04416,96,0,0,1,PC,P212/1,5.043,158
276,2689104,IJ-044,SA04416,14,0,0,1,PC,P212/1,5.043,157
277,2689104,IJ-044,SA04416,11,0,0,1,PC,P212/1,5.043,157
278,2689149,IJ-044,SA07337,27,0,0,1,PC,F420/306,8.733,156
279,2689149,IJ-044,SA07337,18,0,0,1,PC,F420/306,8.733,156
280,2689149,IJ-044,SA07337,97,0,0,1,PC,F420/306,8.733,152
281,2689149,IJ-044,SA07337,161,18,0,1,PC,F420/306,8.733,152
282,2689149,IJ-044,SA07337,121,13,0,1,PC,F420/306,8.733,151
283,2689149,IJ-044,SA07337,250,0,0,1,PC,F420/306,8.733,151
284,2689149,IJ-044,SA07337,52,0,0,1,PC,F420/306,8.733,151
285,2689149,IJ-044,SA07337,157,0,0,1,PC,F420/306,8.733,150
286,2689149,IJ-044,SA07337,304,0,0,1,PC,F420/306,8.733,150
287,2689149,IJ-044,SA07337,181,4,0,1,PC,F420/306,8.733,150
288,2689149,IJ-044,SA07337,78,3,0,1,PC,F420/306,8.733,150
289,2689149,IJ-044,SA07337,114,5,0,1,PC,F420/306,8.733,149
290,2689149,IJ-044,SA07337,145,0,0,1,PC,F420/306,8.733,149
291,2689149,IJ-044,SA07337,251,8,0,1,PC,F420/306,8.733,149
292,2689149,IJ-044,SA07337,177,0,0,1,PC,F420/306,8.733,148
293,2689149,IJ-044,SA07337,3,0,0,1,PC,F420/306,8.733,146
294,2689149,IJ-044,SA07337,135,3,0,1,PC,F420/306,8.733,145
295,2689592,IJ-044,SA04417,32,18,0,1,PC,F420/306,8.773,145
296,2689592,IJ-044,SA04417,275,0,0,1,PC,F420/306,8.773,145
297,2689592,IJ-044,SA04417,102,7,0,1,PC,F420/306,8.773,145
298,2689592,IJ-044,SA04417,134,6,0,1,PC,F420/306,8.773,144
299,2689592,IJ-044,SA04417,264,0,0,1,PC,F420/306,8.773,144
300,2689592,IJ-044,SA04417,107,2,0,1,PC,F420/306,8.773,144
301,2689592,IJ-044,SA04417,56,13,0,1,PC,F420/306,8.773,144
302,2689592,IJ-044,SA04417,21,3,0,1,PC,F420/306,8.773,143
303,2689592,IJ-044,SA04417,233,0,0,1,PC,F420/306,8.773,143
304,2689592,IJ-044,SA04417,226,13,0,1,PC,F420/306,8.773,143
305,2689592,IJ-044,SA04417,114,0,0,1,PC,F420/306,8.773,142
306,2689592,IJ-044,SA04417,8,0,0,1,PC,F420/306,8.773,142
307,2690225,IJ-044,SA04416,183,0,0,1,PC,P212/1,5.043,142
308,2690225,IJ-044,SA04416,191,0,0,1,PC,P212/1,5.043,142
309,2690225,IJ-044,SA04416,262,0,0,1,PC,P212/1,5.043,141
310,2690225,IJ-044,SA04416,275,14,0,1,PC,P212/1,5.043,141
311,2690225,IJ-044,SA04416,14,0,0,1,PC,P212/1,5.043,141
312,2690225,IJ-044,SA04416,122,1,0,1,PC,P212/1,5.043,140
313,2690225,IJ-044,SA04416,231,0,0,1,PC,P212/1,5.043,139
314,2690225,IJ-044,SA04416,308,0,0,1,PC,P212/1,5.043,139
315,2690225,IJ-044,SA04416,259,16,0,1,PC,P212/1,5.043,139
316,2690225,IJ-044,SA04416,192,5,0,1,PC,P212/1,5.043,138
317,2690225,IJ-044,SA04416,304,0,0,1,PC,P212/1,5.043,138
318,2690225,IJ-044,SA04416,382,7,0,1,PC,P212/1,5.043,138
319,2690225,IJ-044,SA04416,177,0,0,1,PC,P212/1,5.043,137
320,2690225,IJ-044,SA04416,319,0,0,1,PC,P212/1,5.043,137
321,2690225,IJ-044,SA04416,319,10,0,1,PC,P212/1,5.043,137
322,2690225,IJ-044,SA04416,187,0,0,1,PC,P212/1,5.043,136
323,2690225,IJ-044,SA04416,323,0,0,1,PC,P212/1,5.043,136
324,2690225,IJ-044,SA04416,285,6,0,1,PC,P212/1,5.043,136
325,2690225,IJ-044,SA04416,2,0,0,1,PC,P212/1,5.043,135
326,2690225,IJ-044,SA04416,168,0,0,1,PC,P212/1,5.043,135
327,2690225,IJ-044,SA04416,320,0,0,1,PC,P212/1,5.043,135
328,2690225,IJ-044,SA04416,312,7,0,1,PC,P212/1,5.043,135
329,2690225,IJ-044,SA04416,275,0,0,1,PC,P212/1,5.043,134
330,2690225,IJ-044,SA04416,268,4,0,1,PC,P212/1,5.043,134
331,2690093,IJ-044,SA02900,43,28,0,1,PC,F420/306,2.616,133
332,2690093,IJ-044,SA02900,165,14,0,1,PC,F420/306,2.616,132
333,2690093,IJ-044,SA02900,297,28,0,1,PC,F420/306,2.616,132
334,2690093,IJ-044,SA02900,173,19,0,1,PC,F420/306,2.616,132
335,2690093,IJ-044,SA02900,176,3,0,1,PC,F420/306,2.616,131
336,2690093,IJ-044,SA02900,216,43,0,1,PC,F420/306,2.616,131
337,2690093,IJ-044,SA02900,316,15,0,1,PC,F420/306,2.616,131
338,2690093,IJ-044,SA02900,260,0,0,1,PC,F420/306,2.616,130
339,2690093,IJ-044,SA02900,320,8,0,1,PC,F420/306,2.616,130
340,2690149,IJ-044,SA02583,3,0,0,1,PC,F403/32,6.760,130
341,2690149,IJ-044,SA02583,13,0,0,1,PC,F403/32,6.760,129
342,2690434,IJ-044,SA07337,45,0,0,1,PC,F420/306,8.733,129
343,2690434,IJ-044,SA07337,194,0,0,1,PC,F420/306,8.733,129
344,2690434,IJ-044,SA07337,258,0,0,1,PC,F420/306,8.733,128

In [7]:
df.to_csv("mnt-" + file_, index=False)

In [8]:
# Display the first 5 rows
print(df.head().to_markdown(index=False, numalign="left", stralign="left"))

# Print the column names and their data types
print(df.info())

| Cód. Ordem   | Cód. Recurso   | Cód. Produto   | Qtd. Produzida   | Qtd. Refugada   | Qtd. Retrabalhada   | Fator Un.   | Cód. Un.   | Descrição da massa (Composto)   | Consumo de massa no item em (Kg/100pçs)   | Manutencao   |
|:-------------|:---------------|:---------------|:-----------------|:----------------|:--------------------|:------------|:-----------|:--------------------------------|:------------------------------------------|:-------------|
| 2680830      | IJ-044         | SA08395        | 239              | 4               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 279          |
| 2680830      | IJ-044         | SA08395        | 158              | 6               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 279          |
| 2680830      | IJ-044         | SA08395        | 471              | 11              | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 279          |
| 2680830      | IJ-044         | SA08395        | 479              | 3               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 278          |
| 2680830      | IJ-044         | SA08395        | 97               | 3               | 0                   | 1           | PC         | N-142/67                        | 2.869                                     | 278          |
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cód. Ordem                               610 non-null    int64
 1   Cód. Recurso                             610 non-null    object
 2   Cód. Produto                             610 non-null    object
 3   Qtd. Produzida                           610 non-null    int64
 4   Qtd. Refugada                            610 non-null    int64
 5   Qtd. Retrabalhada                        610 non-null    int64
 6   Fator Un.                                610 non-null    int64
 7   Cód. Un.                                 610 non-null    object
 8   Descrição da massa (Composto)            610 non-null    object
 9   Consumo de massa no item em (Kg/100pçs)  610 non-null    float64
 10  Manutencao                               610 non-null    int64
dtypes: float64(1), int64(6), object(4)
memory usage: 52.5+ KB
None

In [9]:
# Sort by `Manutencao`
df.sort_values(by="Manutencao", inplace=True)

# Group by `Manutencao` and calculate the cumulative sum for the specified columns
df["Qtd. Produzida"] = df.groupby("Manutencao")["Qtd. Produzida"].cumsum()
df["Qtd. Refugada"] = df.groupby("Manutencao")["Qtd. Refugada"].cumsum()
df["Qtd. Retrabalhada"] = df.groupby("Manutencao")["Qtd. Retrabalhada"].cumsum()
df["Fator Un."] = df.groupby("Manutencao")["Fator Un."].cumsum()
df["Consumo de massa no item em (Kg/100pçs)"] = df.groupby("Manutencao")[
    "Consumo de massa no item em (Kg/100pçs)"
].cumsum()

# Display the first 5 rows of the resulting data
print(df.head().to_markdown(index=False, numalign="left", stralign="left"))

# Print the column names and their data types
print(df.info())

| Cód. Ordem   | Cód. Recurso   | Cód. Produto   | Qtd. Produzida   | Qtd. Refugada   | Qtd. Retrabalhada   | Fator Un.   | Cód. Un.   | Descrição da massa (Composto)   | Consumo de massa no item em (Kg/100pçs)   | Manutencao   |
|:-------------|:---------------|:---------------|:-----------------|:----------------|:--------------------|:------------|:-----------|:--------------------------------|:------------------------------------------|:-------------|
| 2697563      | IJ-044         | SA07371        | 114              | 4               | 0                   | 1           | PC         | F424/85                         | 7                                         | 0            |
| 2697563      | IJ-044         | SA07371        | 234              | 0               | 0                   | 1           | PC         | F424/85                         | 7                                         | 1            |
| 2697563      | IJ-044         | SA07371        | 412              | 0               | 0                   | 2           | PC         | F424/85                         | 14                                        | 1            |
| 2697563      | IJ-044         | SA07371        | 1                | 0               | 0                   | 1           | PC         | F424/85                         | 7                                         | 2            |
| 2697563      | IJ-044         | SA07371        | 227              | 8               | 0                   | 2           | PC         | F424/85                         | 14                                        | 2            |
<class 'pandas.core.frame.DataFrame'>
Index: 610 entries, 609 to 0
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cód. Ordem                               610 non-null    int64
 1   Cód. Recurso                             610 non-null    object
 2   Cód. Produto                             610 non-null    object
 3   Qtd. Produzida                           610 non-null    int64
 4   Qtd. Refugada                            610 non-null    int64
 5   Qtd. Retrabalhada                        610 non-null    int64
 6   Fator Un.                                610 non-null    int64
 7   Cód. Un.                                 610 non-null    object
 8   Descrição da massa (Composto)            610 non-null    object
 9   Consumo de massa no item em (Kg/100pçs)  610 non-null    float64
 10  Manutencao                               610 non-null    int64
dtypes: float64(1), int64(6), object(4)
memory usage: 57.2+ KB
None

In [10]:
# Group by `Manutencao` and calculate the last values for the specified columns
df_result = df.groupby("Manutencao").last().reset_index()

# Display the first 5 rows of the resulting data
print(df_result.head().to_markdown(index=False, numalign="left", stralign="left"))

# Print the column names and their data types
print(df_result.info())

| Manutencao   | Cód. Ordem   | Cód. Recurso   | Cód. Produto   | Qtd. Produzida   | Qtd. Refugada   | Qtd. Retrabalhada   | Fator Un.   | Cód. Un.   | Descrição da massa (Composto)   | Consumo de massa no item em (Kg/100pçs)   |
|:-------------|:-------------|:---------------|:---------------|:-----------------|:----------------|:--------------------|:------------|:-----------|:--------------------------------|:------------------------------------------|
| 0            | 2697563      | IJ-044         | SA07371        | 114              | 4               | 0                   | 1           | PC         | F424/85                         | 7                                         |
| 1            | 2697563      | IJ-044         | SA07371        | 412              | 0               | 0                   | 2           | PC         | F424/85                         | 14                                        |
| 2            | 2697563      | IJ-044         | SA07371        | 492              | 11              | 0                   | 4           | PC         | F424/85                         | 28                                        |
| 3            | 2697563      | IJ-044         | SA07371        | 618              | 9               | 0                   | 3           | PC         | F424/85                         | 21                                        |
| 4            | 2697563      | IJ-044         | SA07371        | 585              | 20              | 0                   | 4           | PC         | F424/85                         | 28                                        |
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Manutencao                               230 non-null    int64
 1   Cód. Ordem                               230 non-null    int64
 2   Cód. Recurso                             230 non-null    object
 3   Cód. Produto                             230 non-null    object
 4   Qtd. Produzida                           230 non-null    int64
 5   Qtd. Refugada                            230 non-null    int64
 6   Qtd. Retrabalhada                        230 non-null    int64
 7   Fator Un.                                230 non-null    int64
 8   Cód. Un.                                 230 non-null    object
 9   Descrição da massa (Composto)            230 non-null    object
 10  Consumo de massa no item em (Kg/100pçs)  230 non-null    float64
dtypes: float64(1), int64(6), object(4)
memory usage: 19.9+ KB
None

In [11]:
# Sort the dataframe by `Manutencao` in descending order
df_sorted = df_result.sort_values(by="Manutencao", ascending=False)

# Print the first 5 rows of the sorted dataframe
print(df_sorted.head().to_markdown(index=False, numalign="left", stralign="left"))

| Manutencao   | Cód. Ordem   | Cód. Recurso   | Cód. Produto   | Qtd. Produzida   | Qtd. Refugada   | Qtd. Retrabalhada   | Fator Un.   | Cód. Un.   | Descrição da massa (Composto)   | Consumo de massa no item em (Kg/100pçs)   |
|:-------------|:-------------|:---------------|:---------------|:-----------------|:----------------|:--------------------|:------------|:-----------|:--------------------------------|:------------------------------------------|
| 279          | 2680830      | IJ-044         | SA08395        | 868              | 21              | 0                   | 3           | PC         | N-142/67                        | 8.607                                     |
| 278          | 2680830      | IJ-044         | SA08395        | 1014             | 15              | 0                   | 4           | PC         | N-142/67                        | 9.157                                     |
| 277          | 2680534      | IJ-044         | SA07321        | 802              | 46              | 0                   | 3           | PC         | N148/18                         | 4.35                                      |
| 276          | 2680534      | IJ-044         | SA07321        | 907              | 18              | 0                   | 3           | PC         | N148/18                         | 5.7                                       |
| 275          | 2680830      | IJ-044         | SA08395        | 1033             | 16              | 0                   | 5           | PC         | N-142/67                        | 12.407                                    |

In [12]:
# Group by `Manutencao` and calculate the last values for the specified columns
df_result = df.groupby("Manutencao").last().reset_index()

# Reorder columns to place 'Manutencao' last
cols = df_result.columns.tolist()
cols.remove("Manutencao")
cols.append("Manutencao")
df_result = df_result[cols]

# Display the first 5 rows of the resulting data
print(df_result.head().to_markdown(index=False, numalign="left", stralign="left"))

# Print the column names and their data types
print(df_result.info())

| Cód. Ordem   | Cód. Recurso   | Cód. Produto   | Qtd. Produzida   | Qtd. Refugada   | Qtd. Retrabalhada   | Fator Un.   | Cód. Un.   | Descrição da massa (Composto)   | Consumo de massa no item em (Kg/100pçs)   | Manutencao   |
|:-------------|:---------------|:---------------|:-----------------|:----------------|:--------------------|:------------|:-----------|:--------------------------------|:------------------------------------------|:-------------|
| 2697563      | IJ-044         | SA07371        | 114              | 4               | 0                   | 1           | PC         | F424/85                         | 7                                         | 0            |
| 2697563      | IJ-044         | SA07371        | 412              | 0               | 0                   | 2           | PC         | F424/85                         | 14                                        | 1            |
| 2697563      | IJ-044         | SA07371        | 492              | 11              | 0                   | 4           | PC         | F424/85                         | 28                                        | 2            |
| 2697563      | IJ-044         | SA07371        | 618              | 9               | 0                   | 3           | PC         | F424/85                         | 21                                        | 3            |
| 2697563      | IJ-044         | SA07371        | 585              | 20              | 0                   | 4           | PC         | F424/85                         | 28                                        | 4            |
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cód. Ordem                               230 non-null    int64
 1   Cód. Recurso                             230 non-null    object
 2   Cód. Produto                             230 non-null    object
 3   Qtd. Produzida                           230 non-null    int64
 4   Qtd. Refugada                            230 non-null    int64
 5   Qtd. Retrabalhada                        230 non-null    int64
 6   Fator Un.                                230 non-null    int64
 7   Cód. Un.                                 230 non-null    object
 8   Descrição da massa (Composto)            230 non-null    object
 9   Consumo de massa no item em (Kg/100pçs)  230 non-null    float64
 10  Manutencao                               230 non-null    int64
dtypes: float64(1), int64(6), object(4)
memory usage: 19.9+ KB
None

In [13]:
# Sort the dataframe by `Manutencao` in descending order
df_sorted = df_result.sort_values(by="Manutencao", ascending=False)
df_sorted

,Cód. Ordem,Cód. Recurso,Cód. Produto,Qtd. Produzida,Qtd. Refugada,Qtd. Retrabalhada,Fator Un.,Cód. Un.,Descrição da massa (Composto),Consumo de massa no item em (Kg/100pçs),Manutencao
229,2680830,IJ-044,SA08395,868,21,0,3,PC,N-142/67,8.607,279
228,2680830,IJ-044,SA08395,1014,15,0,4,PC,N-142/67,9.157,278
227,2680534,IJ-044,SA07321,802,46,0,3,PC,N148/18,4.350,277
226,2680534,IJ-044,SA07321,907,18,0,3,PC,N148/18,5.700,276
225,2680830,IJ-044,SA08395,1033,16,0,5,PC,N-142/67,12.407,275
224,2680830,IJ-044,SA08395,163,1,0,1,PC,N-142/67,2.869,273
223,2680830,IJ-044,SA08395,753,16,0,4,PC,N-142/67,8.918,272
222,2682010,IJ-044,SA01801,790,33,0,4,PC,N146/9,9.940,271
221,2680332,IJ-044,SA02941,310,13,0,3,PC,N148/18,10.140,270
220,2680332,IJ-044,SA02941,749,15,0,3,PC,N148/18,10.140,269
219,2680332,IJ-044,SA02941,89,3,0,1,PC,N148/18,3.380,268
218,2680332,IJ-044,SA02941,723,10,0,3,PC,N148/18,10.140,261
217,2680332,IJ-044,SA02941,138,4,0,1,PC,N148/18,3.380,259
216,2680332,IJ-044,SA02941,970,18,0,3,PC,N148/18,10.140,258
215,2680332,IJ-044,SA02941,865,17,0,3,PC,N148/18,10.140,257
214,2680332,IJ-044,SA02941,875,25,0,3,PC,N148/18,10.140,256
213,2680332,IJ-044,SA02941,775,10,0,3,PC,N148/18,10.140,255
212,2680332,IJ-044,SA02941,789,14,0,3,PC,N148/18,10.140,254
211,2680332,IJ-044,SA02941,176,3,0,2,PC,N148/18,6.760,252
210,2683450,IJ-044,SA02941,1067,12,0,5,PC,N148/18,16.674,251
209,2683569,IJ-044,11974,758,21,0,3,PC,N-158/3,9.462,250
208,2683666,IJ-044,SA07321,346,6,0,3,PC,N148/18,6.954,249
207,2682511,IJ-044,SA04416,498,20,0,3,PC,P212/1,8.843,248
206,2682511,IJ-044,SA04416,240,2,0,2,PC,P212/1,10.086,247
205,2682511,IJ-044,SA04416,268,2,0,3,PC,P212/1,15.129,246
204,2682511,IJ-044,SA04416,590,12,0,3,PC,P212/1,15.129,244
203,2682511,IJ-044,SA04416,614,10,0,3,PC,P212/1,15.129,243
202,2682511,IJ-044,SA04416,704,7,0,3,PC,P212/1,15.129,242
201,2682511,IJ-044,SA04416,784,5,0,3,PC,P212/1,15.129,241
200,2682511,IJ-044,SA04416,674,9,0,3,PC,P212/1,15.129,240
199,2682511,IJ-044,SA04416,93,0,0,1,PC,P212/1,5.043,239
198,2684278,IJ-044,SA11684,663,42,0,6,PC,N148/18,11.293,237
197,2684451,IJ-044,SA02938,702,11,0,4,PC,N-142/67,10.200,236
196,2684451,IJ-044,SA02938,657,7,0,3,PC,N-142/67,7.650,235
195,2684451,IJ-044,SA02938,684,18,0,3,PC,N-142/67,7.650,234
194,2684656,IJ-044,SA00436,709,14,0,3,PC,N-142/67,6.106,233
193,2684656,IJ-044,SA00436,646,34,0,4,PC,N-142/67,4.024,230
192,2684656,IJ-044,SA00436,377,19,0,2,PC,N-142/67,2.012,229
191,2684656,IJ-044,SA00436,343,0,0,2,PC,N-142/67,2.012,228
190,2684656,IJ-044,SA00436,1017,8,0,3,PC,N-142/67,3.018,226
189,2684656,IJ-044,SA00436,34,5,0,1,PC,N-142/67,1.006,224
188,2684451,IJ-044,SA02938,1050,10,0,4,PC,N-142/67,7.112,223
187,2684451,IJ-044,SA02938,787,18,0,3,PC,N-142/67,7.650,222
186,2684451,IJ-044,SA02938,319,2,0,3,PC,N-142/67,3.892,221
185,2685583,IJ-044,SA18476,618,5,0,5,PC,N-142/67,2.618,220
184,2685583,IJ-044,SA18476,675,16,0,5,PC,N-142/67,7.191,219
183,2685610,IJ-044,SA01974,57,8,0,1,PC,N148/18,2.820,217
182,2685610,IJ-044,SA01974,755,11,0,3,PC,N148/18,8.460,216
181,2685610,IJ-044,SA01974,731,14,0,3,PC,N148/18,8.460,215
180,2685610,IJ-044,SA01974,930,1,0,3,PC,N148/18,8.460,214
179,2685803,IJ-044,SA02910,1070,22,0,3,PC,N148/18,1.860,213
178,2685767,IJ-044,SA03682,763,19,0,3,PC,N148/18,18.000,212
177,2685767,IJ-044,SA03682,619,11,0,3,PC,N148/18,18.000,209
176,2685767,IJ-044,SA03682,800,10,0,4,PC,N148/18,17.100,208
175,2684451,IJ-044,SA02938,1017,13,0,4,PC,N-142/67,10.200,207
174,2684451,IJ-044,SA02938,402,6,0,2,PC,N-142/67,5.100,202
173,2684451,IJ-044,SA02938,810,9,0,3,PC,N-142/67,7.650,201
172,2684451,IJ-044,SA02938,475,17,0,8,PC,N-142/67,37.851,200
171,2686201,IJ-044,SA04416,633,16,0,3,PC,P212/1,15.129,199
170,2686201,IJ-044,SA04416,617,15,0,5,PC,P212/1,25.215,198
169,2686201,IJ-044,SA04416,481,14,0,3,PC,P212/1,15.129,197
168,2686201,IJ-044,SA04416,86,7,0,1,PC,P212/1,5.043,196
167,2686201,IJ-044,SA04416,665,8,0,3,PC,P212/1,15.129,195
166,2686201,IJ-044,SA04416,697,5,0,3,PC,P212/1,15.129,194
165,2686201,IJ-044,SA04416,281,0,0,2,PC,P212/1,10.086,193
164,2686201,IJ-044,SA04416,801,9,0,3,PC,P212/1,15.129,192
163,2686201,IJ-044,SA04416,780,3,0,3,PC,P212/1,15.129,191
162,2686201,IJ-044,SA04416,2,0,0,1,PC,P212/1,5.043,189
161,2686773,IJ-044,SA07337,229,21,0,3,PC,F420/306,22.509,188
160,2686773,IJ-044,SA07337,420,16,0,3,PC,F420/306,26.199,187
159,2686773,IJ-044,SA07337,718,11,0,3,PC,F420/306,26.199,186
158,2686201,IJ-044,SA04416,496,25,0,4,PC,P212/1,23.862,185
157,2686201,IJ-044,SA04416,863,1,0,3,PC,P212/1,15.129,184
156,2686201,IJ-044,SA04416,564,6,0,2,PC,P212/1,10.086,183
155,2686201,IJ-044,SA04416,145,2,0,1,PC,P212/1,5.043,182
154,2686201,IJ-044,SA04416,869,5,0,3,PC,P212/1,15.129,181
153,2686201,IJ-044,SA04416,706,3,0,3,PC,P212/1,15.129,180
152,2686201,IJ-044,SA04416,873,8,0,3,PC,P212/1,15.129,179
151,2686201,IJ-044,SA04416,868,1,0,3,PC,P212/1,15.129,178
150,2686201,IJ-044,SA04416,813,10,0,3,PC,P212/1,22.589,177
149,2687844,IJ-044,SA04417,330,7,0,2,PC,F420/306,17.546,174
148,2687845,IJ-044,SA04416,1382,5,0,2,PC,P212/1,10.086,173
147,2687845,IJ-044,SA04416,665,3,0,3,PC,P212/1,15.129,172
146,2687845,IJ-044,SA04416,871,4,0,3,PC,P212/1,15.129,171
145,2687845,IJ-044,SA04416,717,4,0,3,PC,P212/1,15.129,170
144,2686826,IJ-044,SA02583,149,1,0,1,PC,F403/32,6.760,168
143,2686826,IJ-044,SA02583,58,0,0,2,PC,F403/32,11.803,167
142,2686826,IJ-044,SA02583,22,0,0,1,PC,F403/32,6.760,166
141,2686826,IJ-044,SA02583,26,0,0,2,PC,F403/32,13.520,165
140,2686826,IJ-044,SA02583,21,0,0,2,PC,F403/32,13.520,164
139,2689104,IJ-044,SA04416,58,20,0,3,PC,P212/1,15.129,163
138,2689104,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,161
137,2689104,IJ-044,SA04416,718,22,0,3,PC,P212/1,15.129,160
136,2689104,IJ-044,SA04416,414,26,0,3,PC,P212/1,15.129,159
135,2689104,IJ-044,SA04416,556,4,0,3,PC,P212/1,15.129,158
134,2689104,IJ-044,SA04416,25,0,0,2,PC,P212/1,10.086,157
133,2689149,IJ-044,SA07337,45,0,0,2,PC,F420/306,17.466,156
132,2689149,IJ-044,SA07337,258,18,0,2,PC,F420/306,17.466,152
131,2689149,IJ-044,SA07337,423,13,0,3,PC,F420/306,26.199,151
130,2689149,IJ-044,SA07337,720,7,0,4,PC,F420/306,34.932,150
129,2689149,IJ-044,SA07337,510,13,0,3,PC,F420/306,26.199,149
128,2689149,IJ-044,SA07337,177,0,0,1,PC,F420/306,8.733,148
127,2689149,IJ-044,SA07337,3,0,0,1,PC,F420/306,8.733,146
126,2689592,IJ-044,SA04417,544,28,0,4,PC,F420/306,35.052,145
125,2689592,IJ-044,SA04417,561,21,0,4,PC,F420/306,35.092,144
124,2689592,IJ-044,SA04417,480,16,0,3,PC,F420/306,26.319,143
123,2689592,IJ-044,SA04417,496,0,0,4,PC,F420/306,27.632,142
122,2690225,IJ-044,SA04416,551,14,0,3,PC,P212/1,15.129,141
121,2690225,IJ-044,SA04416,122,1,0,1,PC,P212/1,5.043,140
120,2690225,IJ-044,SA04416,798,16,0,3,PC,P212/1,15.129,139
119,2690225,IJ-044,SA04416,878,12,0,3,PC,P212/1,15.129,138
118,2690225,IJ-044,SA04416,815,10,0,3,PC,P212/1,15.129,137
117,2690225,IJ-044,SA04416,795,6,0,3,PC,P212/1,15.129,136
116,2690225,IJ-044,SA04416,802,7,0,4,PC,P212/1,20.172,135
115,2690225,IJ-044,SA04416,543,4,0,2,PC,P212/1,10.086,134
114,2690093,IJ-044,SA02900,43,28,0,1,PC,F420/306,2.616,133
113,2690093,IJ-044,SA02900,635,61,0,3,PC,F420/306,7.848,132
112,2690093,IJ-044,SA02900,708,61,0,3,PC,F420/306,7.848,131
111,2690093,IJ-044,SA02900,583,8,0,3,PC,F420/306,11.992,130
110,2690434,IJ-044,SA07337,252,0,0,3,PC,F420/306,24.226,129
109,2690434,IJ-044,SA07337,428,10,0,2,PC,F420/306,17.466,128
108,2690434,IJ-044,SA07337,216,0,0,1,PC,F420/306,8.733,127
107,2690434,IJ-044,SA07337,95,18,0,1,PC,F420/306,8.733,126
106,2690434,IJ-044,SA07337,657,19,0,3,PC,F420/306,26.199,125
105,2690140,IJ-044,SA07339,465,10,0,3,PC,F420/306,24.055,124
104,2690140,IJ-044,SA07339,600,26,0,3,PC,F420/306,19.767,123
103,2690140,IJ-044,SA07339,792,10,0,3,PC,F420/306,19.767,122
102,2690140,IJ-044,SA07339,110,2,0,1,PC,F420/306,6.589,121
101,2690140,IJ-044,SA07339,2,0,0,1,PC,F420/306,6.589,119
100,2690225,IJ-044,SA04416,502,7,0,3,PC,P212/1,16.675,118
99,2690225,IJ-044,SA04416,780,18,0,3,PC,P212/1,15.129,117
98,2690225,IJ-044,SA04416,799,8,0,3,PC,P212/1,15.129,116
97,2690225,IJ-044,SA04416,818,6,0,3,PC,P212/1,15.129,115
96,2690225,IJ-044,SA04416,341,1,0,2,PC,P212/1,8.317,114
95,2691658,IJ-044,SA02619,74,15,0,1,PC,F420/96,3.274,112
94,2690225,IJ-044,SA04416,291,23,0,3,PC,P212/1,13.360,111
93,2690225,IJ-044,SA04416,764,11,0,3,PC,P212/1,15.129,110
92,2690225,IJ-044,SA04416,651,13,0,3,PC,P212/1,15.129,109
91,2690225,IJ-044,SA04416,753,9,0,3,PC,P212/1,15.129,108
90,2690225,IJ-044,SA04416,190,4,0,1,PC,P212/1,5.043,107
89,2690225,IJ-044,SA04416,241,13,0,2,PC,P212/1,10.086,103
88,2690225,IJ-044,SA04416,801,11,0,3,PC,P212/1,15.129,102
87,2690225,IJ-044,SA04416,811,14,0,3,PC,P212/1,15.129,101
86,2690225,IJ-044,SA04416,804,4,0,3,PC,P212/1,15.129,100
85,2690225,IJ-044,SA04416,246,7,0,1,PC,P212/1,5.043,99
84,2690225,IJ-044,SA04416,148,0,0,1,PC,P212/1,5.043,98
83,2690225,IJ-044,SA04416,375,32,0,2,PC,P212/1,10.086,97
82,2690225,IJ-044,SA04416,13,0,0,1,PC,P212/1,5.043,95
81,2691658,IJ-044,SA02619,304,20,0,2,PC,F420/96,6.548,93
80,2691658,IJ-044,SA02619,130,0,0,1,PC,F420/96,3.274,91
79,2691334,IJ-044,SA04416,299,62,0,4,PC,P212/1,16.634,90
78,2691334,IJ-044,SA04416,162,14,0,1,PC,P212/1,5.043,89
77,2692988,IJ-044,SA07291,40,50,0,1,PC,F403/32,3.500,88
76,2692988,IJ-044,SA07291,5,16,0,1,PC,F403/32,3.500,87
75,2693639,IJ-044,SA04416,302,16,0,2,PC,P212/1,10.086,81
74,2693639,IJ-044,SA04416,421,17,0,3,PC,P212/1,15.129,80
73,2693639,IJ-044,SA04416,624,26,0,3,PC,P212/1,15.129,79
72,2693639,IJ-044,SA04416,258,2,0,1,PC,P212/1,5.043,78
71,2693639,IJ-044,SA04416,155,0,0,1,PC,P212/1,5.043,77
70,2693639,IJ-044,SA04416,762,23,0,3,PC,P212/1,15.129,76
69,2693639,IJ-044,SA04416,768,13,0,3,PC,P212/1,15.129,75
68,2693639,IJ-044,SA04416,609,9,0,3,PC,P212/1,15.129,74
67,2693639,IJ-044,SA04416,595,9,0,3,PC,P212/1,15.129,73
66,2693639,IJ-044,SA04416,618,8,0,2,PC,P212/1,10.086,72
65,2693639,IJ-044,SA04416,128,5,0,1,PC,P212/1,5.043,70
64,2693639,IJ-044,SA04416,670,18,0,3,PC,P212/1,15.129,69
63,2693639,IJ-044,SA04416,36,0,0,1,PC,P212/1,5.043,68
62,2693639,IJ-044,SA04416,561,7,0,3,PC,P212/1,15.129,67
61,2693639,IJ-044,SA04416,508,1,0,3,PC,P212/1,15.129,66
60,2693639,IJ-044,SA04416,732,2,0,4,PC,P212/1,20.172,65
59,2693639,IJ-044,SA04416,88,0,0,1,PC,P212/1,5.043,64
58,2693639,IJ-044,SA04416,814,5,0,3,PC,P212/1,15.129,62
57,2693639,IJ-044,SA04416,482,0,0,2,PC,P212/1,10.086,61
56,2693639,IJ-044,SA04416,463,24,0,3,PC,P212/1,15.129,60
55,2693639,IJ-044,SA04416,777,19,0,3,PC,P212/1,15.129,59
54,2693639,IJ-044,SA04416,535,6,0,3,PC,P212/1,15.129,58
53,2693639,IJ-044,SA04416,260,12,0,1,PC,P212/1,5.043,57
52,2693639,IJ-044,SA04416,118,3,0,1,PC,P212/1,5.043,56
51,2693639,IJ-044,SA04416,822,6,0,3,PC,P212/1,15.129,55
50,2694422,IJ-044,SA02973,269,12,0,3,PC,F403/32,10.843,54
49,2694422,IJ-044,SA02973,470,7,0,3,PC,F403/32,8.700,53
48,2694422,IJ-044,SA02973,500,43,0,3,PC,F403/32,8.700,52
47,2694422,IJ-044,SA02973,742,12,0,3,PC,F403/32,8.700,51
46,2694422,IJ-044,SA02973,1,0,0,1,PC,F403/32,2.900,49
45,2694422,IJ-044,SA02973,821,7,0,3,PC,F403/32,8.700,48
44,2695553,IJ-044,SA15829,354,19,0,3,PC,F420/191,7.450,47
43,2695553,IJ-044,SA15829,777,46,0,3,PC,F420/191,6.825,46
42,2695553,IJ-044,SA15829,825,29,0,3,PC,F420/191,6.825,45
41,2695553,IJ-044,SA15829,534,42,0,4,PC,F420/191,9.100,44
40,2695553,IJ-044,SA15829,249,5,0,1,PC,F420/191,2.275,43
39,2695553,IJ-044,SA15829,120,0,0,1,PC,F420/191,2.275,42
38,2695455,IJ-044,SA07337,678,20,0,3,PC,F420/306,19.741,41
37,2695455,IJ-044,SA07337,567,32,0,3,PC,F420/306,26.199,40
36,2695455,IJ-044,SA07337,505,40,0,3,PC,F420/306,26.199,39
35,2695455,IJ-044,SA07337,485,25,0,2,PC,F420/306,17.466,38
34,2695455,IJ-044,SA07337,500,21,0,3,PC,F420/306,26.199,37
33,2695455,IJ-044,SA07337,477,2,0,2,PC,F420/306,17.466,36
32,2695455,IJ-044,SA07337,100,4,0,1,PC,F420/306,8.733,35
31,2695455,IJ-044,SA07337,765,14,0,3,PC,F420/306,26.199,34
30,2695455,IJ-044,SA07337,676,10,0,3,PC,F420/306,26.199,33
29,2695085,IJ-044,SA04416,671,29,0,4,PC,P212/1,23.862,32
28,2695085,IJ-044,SA04416,852,7,0,3,PC,P212/1,15.129,31
27,2695085,IJ-044,SA04416,833,2,0,3,PC,P212/1,15.129,30
26,2695085,IJ-044,SA04416,135,3,0,1,PC,P212/1,5.043,28
25,2695085,IJ-044,SA04416,842,9,0,3,PC,P212/1,15.129,27
24,2695085,IJ-044,SA04416,840,6,0,3,PC,P212/1,15.129,26
23,2695085,IJ-044,SA04416,3,0,0,1,PC,P212/1,5.043,25
22,2695085,IJ-044,SA04416,797,20,0,3,PC,P212/1,15.129,24
21,2695085,IJ-044,SA04416,603,10,0,2,PC,P212/1,10.086,23
20,2695085,IJ-044,SA04416,3,0,0,1,PC,P212/1,5.043,21
19,2695085,IJ-044,SA04416,542,18,0,3,PC,P212/1,15.129,20
18,2695085,IJ-044,SA04416,664,11,0,4,PC,P212/1,23.264,19
17,2695456,IJ-044,SA07339,763,7,0,3,PC,F420/306,19.767,18
16,2695456,IJ-044,SA07339,685,6,0,3,PC,F420/306,19.767,17
15,2697109,IJ-044,SA04416,754,11,0,6,PC,P212/1,34.896,16
14,2697109,IJ-044,SA04416,274,4,0,1,PC,P212/1,5.043,15
13,2697109,IJ-044,SA04416,139,6,0,1,PC,P212/1,5.043,14
12,2697109,IJ-044,SA04416,185,3,0,2,PC,P212/1,10.086,13
11,2697109,IJ-044,SA04416,837,10,0,3,PC,P212/1,15.129,12
10,2697109,IJ-044,SA04416,782,19,0,3,PC,P212/1,15.129,11
9,2697109,IJ-044,SA04416,607,9,0,3,PC,P212/1,15.129,10
8,2697109,IJ-044,SA04416,535,11,0,2,PC,P212/1,10.086,9
7,2697563,IJ-044,SA07371,128,1,0,3,PC,F424/85,21.000,8
6,2697563,IJ-044,SA07371,474,17,0,3,PC,F424/85,21.000,6
5,2697563,IJ-044,SA07371,421,6,0,3,PC,F424/85,21.000,5
4,2697563,IJ-044,SA07371,585,20,0,4,PC,F424/85,28.000,4
3,2697563,IJ-044,SA07371,618,9,0,3,PC,F424/85,21.000,3
2,2697563,IJ-044,SA07371,492,11,0,4,PC,F424/85,28.000,2
1,2697563,IJ-044,SA07371,412,0,0,2,PC,F424/85,14.000,1
0,2697563,IJ-044,SA07371,114,4,0,1,PC,F424/85,7.000,0

In [14]:
df_result = df_sorted.reset_index(drop=True)

In [15]:
df_result

,Cód. Ordem,Cód. Recurso,Cód. Produto,Qtd. Produzida,Qtd. Refugada,Qtd. Retrabalhada,Fator Un.,Cód. Un.,Descrição da massa (Composto),Consumo de massa no item em (Kg/100pçs),Manutencao
0,2680830,IJ-044,SA08395,868,21,0,3,PC,N-142/67,8.607,279
1,2680830,IJ-044,SA08395,1014,15,0,4,PC,N-142/67,9.157,278
2,2680534,IJ-044,SA07321,802,46,0,3,PC,N148/18,4.350,277
3,2680534,IJ-044,SA07321,907,18,0,3,PC,N148/18,5.700,276
4,2680830,IJ-044,SA08395,1033,16,0,5,PC,N-142/67,12.407,275
5,2680830,IJ-044,SA08395,163,1,0,1,PC,N-142/67,2.869,273
6,2680830,IJ-044,SA08395,753,16,0,4,PC,N-142/67,8.918,272
7,2682010,IJ-044,SA01801,790,33,0,4,PC,N146/9,9.940,271
8,2680332,IJ-044,SA02941,310,13,0,3,PC,N148/18,10.140,270
9,2680332,IJ-044,SA02941,749,15,0,3,PC,N148/18,10.140,269
10,2680332,IJ-044,SA02941,89,3,0,1,PC,N148/18,3.380,268
11,2680332,IJ-044,SA02941,723,10,0,3,PC,N148/18,10.140,261
12,2680332,IJ-044,SA02941,138,4,0,1,PC,N148/18,3.380,259
13,2680332,IJ-044,SA02941,970,18,0,3,PC,N148/18,10.140,258
14,2680332,IJ-044,SA02941,865,17,0,3,PC,N148/18,10.140,257
15,2680332,IJ-044,SA02941,875,25,0,3,PC,N148/18,10.140,256
16,2680332,IJ-044,SA02941,775,10,0,3,PC,N148/18,10.140,255
17,2680332,IJ-044,SA02941,789,14,0,3,PC,N148/18,10.140,254
18,2680332,IJ-044,SA02941,176,3,0,2,PC,N148/18,6.760,252
19,2683450,IJ-044,SA02941,1067,12,0,5,PC,N148/18,16.674,251
20,2683569,IJ-044,11974,758,21,0,3,PC,N-158/3,9.462,250
21,2683666,IJ-044,SA07321,346,6,0,3,PC,N148/18,6.954,249
22,2682511,IJ-044,SA04416,498,20,0,3,PC,P212/1,8.843,248
23,2682511,IJ-044,SA04416,240,2,0,2,PC,P212/1,10.086,247
24,2682511,IJ-044,SA04416,268,2,0,3,PC,P212/1,15.129,246
25,2682511,IJ-044,SA04416,590,12,0,3,PC,P212/1,15.129,244
26,2682511,IJ-044,SA04416,614,10,0,3,PC,P212/1,15.129,243
27,2682511,IJ-044,SA04416,704,7,0,3,PC,P212/1,15.129,242
28,2682511,IJ-044,SA04416,784,5,0,3,PC,P212/1,15.129,241
29,2682511,IJ-044,SA04416,674,9,0,3,PC,P212/1,15.129,240
30,2682511,IJ-044,SA04416,93,0,0,1,PC,P212/1,5.043,239
31,2684278,IJ-044,SA11684,663,42,0,6,PC,N148/18,11.293,237
32,2684451,IJ-044,SA02938,702,11,0,4,PC,N-142/67,10.200,236
33,2684451,IJ-044,SA02938,657,7,0,3,PC,N-142/67,7.650,235
34,2684451,IJ-044,SA02938,684,18,0,3,PC,N-142/67,7.650,234
35,2684656,IJ-044,SA00436,709,14,0,3,PC,N-142/67,6.106,233
36,2684656,IJ-044,SA00436,646,34,0,4,PC,N-142/67,4.024,230
37,2684656,IJ-044,SA00436,377,19,0,2,PC,N-142/67,2.012,229
38,2684656,IJ-044,SA00436,343,0,0,2,PC,N-142/67,2.012,228
39,2684656,IJ-044,SA00436,1017,8,0,3,PC,N-142/67,3.018,226
40,2684656,IJ-044,SA00436,34,5,0,1,PC,N-142/67,1.006,224
41,2684451,IJ-044,SA02938,1050,10,0,4,PC,N-142/67,7.112,223
42,2684451,IJ-044,SA02938,787,18,0,3,PC,N-142/67,7.650,222
43,2684451,IJ-044,SA02938,319,2,0,3,PC,N-142/67,3.892,221
44,2685583,IJ-044,SA18476,618,5,0,5,PC,N-142/67,2.618,220
45,2685583,IJ-044,SA18476,675,16,0,5,PC,N-142/67,7.191,219
46,2685610,IJ-044,SA01974,57,8,0,1,PC,N148/18,2.820,217
47,2685610,IJ-044,SA01974,755,11,0,3,PC,N148/18,8.460,216
48,2685610,IJ-044,SA01974,731,14,0,3,PC,N148/18,8.460,215
49,2685610,IJ-044,SA01974,930,1,0,3,PC,N148/18,8.460,214
50,2685803,IJ-044,SA02910,1070,22,0,3,PC,N148/18,1.860,213
51,2685767,IJ-044,SA03682,763,19,0,3,PC,N148/18,18.000,212
52,2685767,IJ-044,SA03682,619,11,0,3,PC,N148/18,18.000,209
53,2685767,IJ-044,SA03682,800,10,0,4,PC,N148/18,17.100,208
54,2684451,IJ-044,SA02938,1017,13,0,4,PC,N-142/67,10.200,207
55,2684451,IJ-044,SA02938,402,6,0,2,PC,N-142/67,5.100,202
56,2684451,IJ-044,SA02938,810,9,0,3,PC,N-142/67,7.650,201
57,2684451,IJ-044,SA02938,475,17,0,8,PC,N-142/67,37.851,200
58,2686201,IJ-044,SA04416,633,16,0,3,PC,P212/1,15.129,199
59,2686201,IJ-044,SA04416,617,15,0,5,PC,P212/1,25.215,198
60,2686201,IJ-044,SA04416,481,14,0,3,PC,P212/1,15.129,197
61,2686201,IJ-044,SA04416,86,7,0,1,PC,P212/1,5.043,196
62,2686201,IJ-044,SA04416,665,8,0,3,PC,P212/1,15.129,195
63,2686201,IJ-044,SA04416,697,5,0,3,PC,P212/1,15.129,194
64,2686201,IJ-044,SA04416,281,0,0,2,PC,P212/1,10.086,193
65,2686201,IJ-044,SA04416,801,9,0,3,PC,P212/1,15.129,192
66,2686201,IJ-044,SA04416,780,3,0,3,PC,P212/1,15.129,191
67,2686201,IJ-044,SA04416,2,0,0,1,PC,P212/1,5.043,189
68,2686773,IJ-044,SA07337,229,21,0,3,PC,F420/306,22.509,188
69,2686773,IJ-044,SA07337,420,16,0,3,PC,F420/306,26.199,187
70,2686773,IJ-044,SA07337,718,11,0,3,PC,F420/306,26.199,186
71,2686201,IJ-044,SA04416,496,25,0,4,PC,P212/1,23.862,185
72,2686201,IJ-044,SA04416,863,1,0,3,PC,P212/1,15.129,184
73,2686201,IJ-044,SA04416,564,6,0,2,PC,P212/1,10.086,183
74,2686201,IJ-044,SA04416,145,2,0,1,PC,P212/1,5.043,182
75,2686201,IJ-044,SA04416,869,5,0,3,PC,P212/1,15.129,181
76,2686201,IJ-044,SA04416,706,3,0,3,PC,P212/1,15.129,180
77,2686201,IJ-044,SA04416,873,8,0,3,PC,P212/1,15.129,179
78,2686201,IJ-044,SA04416,868,1,0,3,PC,P212/1,15.129,178
79,2686201,IJ-044,SA04416,813,10,0,3,PC,P212/1,22.589,177
80,2687844,IJ-044,SA04417,330,7,0,2,PC,F420/306,17.546,174
81,2687845,IJ-044,SA04416,1382,5,0,2,PC,P212/1,10.086,173
82,2687845,IJ-044,SA04416,665,3,0,3,PC,P212/1,15.129,172
83,2687845,IJ-044,SA04416,871,4,0,3,PC,P212/1,15.129,171
84,2687845,IJ-044,SA04416,717,4,0,3,PC,P212/1,15.129,170
85,2686826,IJ-044,SA02583,149,1,0,1,PC,F403/32,6.760,168
86,2686826,IJ-044,SA02583,58,0,0,2,PC,F403/32,11.803,167
87,2686826,IJ-044,SA02583,22,0,0,1,PC,F403/32,6.760,166
88,2686826,IJ-044,SA02583,26,0,0,2,PC,F403/32,13.520,165
89,2686826,IJ-044,SA02583,21,0,0,2,PC,F403/32,13.520,164
90,2689104,IJ-044,SA04416,58,20,0,3,PC,P212/1,15.129,163
91,2689104,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,161
92,2689104,IJ-044,SA04416,718,22,0,3,PC,P212/1,15.129,160
93,2689104,IJ-044,SA04416,414,26,0,3,PC,P212/1,15.129,159
94,2689104,IJ-044,SA04416,556,4,0,3,PC,P212/1,15.129,158
95,2689104,IJ-044,SA04416,25,0,0,2,PC,P212/1,10.086,157
96,2689149,IJ-044,SA07337,45,0,0,2,PC,F420/306,17.466,156
97,2689149,IJ-044,SA07337,258,18,0,2,PC,F420/306,17.466,152
98,2689149,IJ-044,SA07337,423,13,0,3,PC,F420/306,26.199,151
99,2689149,IJ-044,SA07337,720,7,0,4,PC,F420/306,34.932,150
100,2689149,IJ-044,SA07337,510,13,0,3,PC,F420/306,26.199,149
101,2689149,IJ-044,SA07337,177,0,0,1,PC,F420/306,8.733,148
102,2689149,IJ-044,SA07337,3,0,0,1,PC,F420/306,8.733,146
103,2689592,IJ-044,SA04417,544,28,0,4,PC,F420/306,35.052,145
104,2689592,IJ-044,SA04417,561,21,0,4,PC,F420/306,35.092,144
105,2689592,IJ-044,SA04417,480,16,0,3,PC,F420/306,26.319,143
106,2689592,IJ-044,SA04417,496,0,0,4,PC,F420/306,27.632,142
107,2690225,IJ-044,SA04416,551,14,0,3,PC,P212/1,15.129,141
108,2690225,IJ-044,SA04416,122,1,0,1,PC,P212/1,5.043,140
109,2690225,IJ-044,SA04416,798,16,0,3,PC,P212/1,15.129,139
110,2690225,IJ-044,SA04416,878,12,0,3,PC,P212/1,15.129,138
111,2690225,IJ-044,SA04416,815,10,0,3,PC,P212/1,15.129,137
112,2690225,IJ-044,SA04416,795,6,0,3,PC,P212/1,15.129,136
113,2690225,IJ-044,SA04416,802,7,0,4,PC,P212/1,20.172,135
114,2690225,IJ-044,SA04416,543,4,0,2,PC,P212/1,10.086,134
115,2690093,IJ-044,SA02900,43,28,0,1,PC,F420/306,2.616,133
116,2690093,IJ-044,SA02900,635,61,0,3,PC,F420/306,7.848,132
117,2690093,IJ-044,SA02900,708,61,0,3,PC,F420/306,7.848,131
118,2690093,IJ-044,SA02900,583,8,0,3,PC,F420/306,11.992,130
119,2690434,IJ-044,SA07337,252,0,0,3,PC,F420/306,24.226,129
120,2690434,IJ-044,SA07337,428,10,0,2,PC,F420/306,17.466,128
121,2690434,IJ-044,SA07337,216,0,0,1,PC,F420/306,8.733,127
122,2690434,IJ-044,SA07337,95,18,0,1,PC,F420/306,8.733,126
123,2690434,IJ-044,SA07337,657,19,0,3,PC,F420/306,26.199,125
124,2690140,IJ-044,SA07339,465,10,0,3,PC,F420/306,24.055,124
125,2690140,IJ-044,SA07339,600,26,0,3,PC,F420/306,19.767,123
126,2690140,IJ-044,SA07339,792,10,0,3,PC,F420/306,19.767,122
127,2690140,IJ-044,SA07339,110,2,0,1,PC,F420/306,6.589,121
128,2690140,IJ-044,SA07339,2,0,0,1,PC,F420/306,6.589,119
129,2690225,IJ-044,SA04416,502,7,0,3,PC,P212/1,16.675,118
130,2690225,IJ-044,SA04416,780,18,0,3,PC,P212/1,15.129,117
131,2690225,IJ-044,SA04416,799,8,0,3,PC,P212/1,15.129,116
132,2690225,IJ-044,SA04416,818,6,0,3,PC,P212/1,15.129,115
133,2690225,IJ-044,SA04416,341,1,0,2,PC,P212/1,8.317,114
134,2691658,IJ-044,SA02619,74,15,0,1,PC,F420/96,3.274,112
135,2690225,IJ-044,SA04416,291,23,0,3,PC,P212/1,13.360,111
136,2690225,IJ-044,SA04416,764,11,0,3,PC,P212/1,15.129,110
137,2690225,IJ-044,SA04416,651,13,0,3,PC,P212/1,15.129,109
138,2690225,IJ-044,SA04416,753,9,0,3,PC,P212/1,15.129,108
139,2690225,IJ-044,SA04416,190,4,0,1,PC,P212/1,5.043,107
140,2690225,IJ-044,SA04416,241,13,0,2,PC,P212/1,10.086,103
141,2690225,IJ-044,SA04416,801,11,0,3,PC,P212/1,15.129,102
142,2690225,IJ-044,SA04416,811,14,0,3,PC,P212/1,15.129,101
143,2690225,IJ-044,SA04416,804,4,0,3,PC,P212/1,15.129,100
144,2690225,IJ-044,SA04416,246,7,0,1,PC,P212/1,5.043,99
145,2690225,IJ-044,SA04416,148,0,0,1,PC,P212/1,5.043,98
146,2690225,IJ-044,SA04416,375,32,0,2,PC,P212/1,10.086,97
147,2690225,IJ-044,SA04416,13,0,0,1,PC,P212/1,5.043,95
148,2691658,IJ-044,SA02619,304,20,0,2,PC,F420/96,6.548,93
149,2691658,IJ-044,SA02619,130,0,0,1,PC,F420/96,3.274,91
150,2691334,IJ-044,SA04416,299,62,0,4,PC,P212/1,16.634,90
151,2691334,IJ-044,SA04416,162,14,0,1,PC,P212/1,5.043,89
152,2692988,IJ-044,SA07291,40,50,0,1,PC,F403/32,3.500,88
153,2692988,IJ-044,SA07291,5,16,0,1,PC,F403/32,3.500,87
154,2693639,IJ-044,SA04416,302,16,0,2,PC,P212/1,10.086,81
155,2693639,IJ-044,SA04416,421,17,0,3,PC,P212/1,15.129,80
156,2693639,IJ-044,SA04416,624,26,0,3,PC,P212/1,15.129,79
157,2693639,IJ-044,SA04416,258,2,0,1,PC,P212/1,5.043,78
158,2693639,IJ-044,SA04416,155,0,0,1,PC,P212/1,5.043,77
159,2693639,IJ-044,SA04416,762,23,0,3,PC,P212/1,15.129,76
160,2693639,IJ-044,SA04416,768,13,0,3,PC,P212/1,15.129,75
161,2693639,IJ-044,SA04416,609,9,0,3,PC,P212/1,15.129,74
162,2693639,IJ-044,SA04416,595,9,0,3,PC,P212/1,15.129,73
163,2693639,IJ-044,SA04416,618,8,0,2,PC,P212/1,10.086,72
164,2693639,IJ-044,SA04416,128,5,0,1,PC,P212/1,5.043,70
165,2693639,IJ-044,SA04416,670,18,0,3,PC,P212/1,15.129,69
166,2693639,IJ-044,SA04416,36,0,0,1,PC,P212/1,5.043,68
167,2693639,IJ-044,SA04416,561,7,0,3,PC,P212/1,15.129,67
168,2693639,IJ-044,SA04416,508,1,0,3,PC,P212/1,15.129,66
169,2693639,IJ-044,SA04416,732,2,0,4,PC,P212/1,20.172,65
170,2693639,IJ-044,SA04416,88,0,0,1,PC,P212/1,5.043,64
171,2693639,IJ-044,SA04416,814,5,0,3,PC,P212/1,15.129,62
172,2693639,IJ-044,SA04416,482,0,0,2,PC,P212/1,10.086,61
173,2693639,IJ-044,SA04416,463,24,0,3,PC,P212/1,15.129,60
174,2693639,IJ-044,SA04416,777,19,0,3,PC,P212/1,15.129,59
175,2693639,IJ-044,SA04416,535,6,0,3,PC,P212/1,15.129,58
176,2693639,IJ-044,SA04416,260,12,0,1,PC,P212/1,5.043,57
177,2693639,IJ-044,SA04416,118,3,0,1,PC,P212/1,5.043,56
178,2693639,IJ-044,SA04416,822,6,0,3,PC,P212/1,15.129,55
179,2694422,IJ-044,SA02973,269,12,0,3,PC,F403/32,10.843,54
180,2694422,IJ-044,SA02973,470,7,0,3,PC,F403/32,8.700,53
181,2694422,IJ-044,SA02973,500,43,0,3,PC,F403/32,8.700,52
182,2694422,IJ-044,SA02973,742,12,0,3,PC,F403/32,8.700,51
183,2694422,IJ-044,SA02973,1,0,0,1,PC,F403/32,2.900,49
184,2694422,IJ-044,SA02973,821,7,0,3,PC,F403/32,8.700,48
185,2695553,IJ-044,SA15829,354,19,0,3,PC,F420/191,7.450,47
186,2695553,IJ-044,SA15829,777,46,0,3,PC,F420/191,6.825,46
187,2695553,IJ-044,SA15829,825,29,0,3,PC,F420/191,6.825,45
188,2695553,IJ-044,SA15829,534,42,0,4,PC,F420/191,9.100,44
189,2695553,IJ-044,SA15829,249,5,0,1,PC,F420/191,2.275,43
190,2695553,IJ-044,SA15829,120,0,0,1,PC,F420/191,2.275,42
191,2695455,IJ-044,SA07337,678,20,0,3,PC,F420/306,19.741,41
192,2695455,IJ-044,SA07337,567,32,0,3,PC,F420/306,26.199,40
193,2695455,IJ-044,SA07337,505,40,0,3,PC,F420/306,26.199,39
194,2695455,IJ-044,SA07337,485,25,0,2,PC,F420/306,17.466,38
195,2695455,IJ-044,SA07337,500,21,0,3,PC,F420/306,26.199,37
196,2695455,IJ-044,SA07337,477,2,0,2,PC,F420/306,17.466,36
197,2695455,IJ-044,SA07337,100,4,0,1,PC,F420/306,8.733,35
198,2695455,IJ-044,SA07337,765,14,0,3,PC,F420/306,26.199,34
199,2695455,IJ-044,SA07337,676,10,0,3,PC,F420/306,26.199,33
200,2695085,IJ-044,SA04416,671,29,0,4,PC,P212/1,23.862,32
201,2695085,IJ-044,SA04416,852,7,0,3,PC,P212/1,15.129,31
202,2695085,IJ-044,SA04416,833,2,0,3,PC,P212/1,15.129,30
203,2695085,IJ-044,SA04416,135,3,0,1,PC,P212/1,5.043,28
204,2695085,IJ-044,SA04416,842,9,0,3,PC,P212/1,15.129,27
205,2695085,IJ-044,SA04416,840,6,0,3,PC,P212/1,15.129,26
206,2695085,IJ-044,SA04416,3,0,0,1,PC,P212/1,5.043,25
207,2695085,IJ-044,SA04416,797,20,0,3,PC,P212/1,15.129,24
208,2695085,IJ-044,SA04416,603,10,0,2,PC,P212/1,10.086,23
209,2695085,IJ-044,SA04416,3,0,0,1,PC,P212/1,5.043,21
210,2695085,IJ-044,SA04416,542,18,0,3,PC,P212/1,15.129,20
211,2695085,IJ-044,SA04416,664,11,0,4,PC,P212/1,23.264,19
212,2695456,IJ-044,SA07339,763,7,0,3,PC,F420/306,19.767,18
213,2695456,IJ-044,SA07339,685,6,0,3,PC,F420/306,19.767,17
214,2697109,IJ-044,SA04416,754,11,0,6,PC,P212/1,34.896,16
215,2697109,IJ-044,SA04416,274,4,0,1,PC,P212/1,5.043,15
216,2697109,IJ-044,SA04416,139,6,0,1,PC,P212/1,5.043,14
217,2697109,IJ-044,SA04416,185,3,0,2,PC,P212/1,10.086,13
218,2697109,IJ-044,SA04416,837,10,0,3,PC,P212/1,15.129,12
219,2697109,IJ-044,SA04416,782,19,0,3,PC,P212/1,15.129,11
220,2697109,IJ-044,SA04416,607,9,0,3,PC,P212/1,15.129,10
221,2697109,IJ-044,SA04416,535,11,0,2,PC,P212/1,10.086,9
222,2697563,IJ-044,SA07371,128,1,0,3,PC,F424/85,21.000,8
223,2697563,IJ-044,SA07371,474,17,0,3,PC,F424/85,21.000,6
224,2697563,IJ-044,SA07371,421,6,0,3,PC,F424/85,21.000,5
225,2697563,IJ-044,SA07371,585,20,0,4,PC,F424/85,28.000,4
226,2697563,IJ-044,SA07371,618,9,0,3,PC,F424/85,21.000,3
227,2697563,IJ-044,SA07371,492,11,0,4,PC,F424/85,28.000,2
228,2697563,IJ-044,SA07371,412,0,0,2,PC,F424/85,14.000,1
229,2697563,IJ-044,SA07371,114,4,0,1,PC,F424/85,7.000,0

In [16]:
df_result.to_csv("mnt-grouped-" + file_, index=False)

In [17]:
# Calculate the cumulative sum for the specified columns and store them in new columns
df_result["Qtd. Produzida Acumulada Total"] = df_result["Qtd. Produzida"].cumsum()
df_result["Qtd. Refugada Acumulada Total"] = df_result["Qtd. Refugada"].cumsum()
df_result["Qtd. Retrabalhada Acumulada Total"] = df_result["Qtd. Retrabalhada"].cumsum()
df_result["Fator Un. Acumulado Total"] = df_result["Fator Un."].cumsum()
df_result["Consumo de massa no item em (Kg/100pçs) Acumulado Total"] = df_result[
    "Consumo de massa no item em (Kg/100pçs)"
].cumsum()

In [18]:
df_result

,Cód. Ordem,Cód. Recurso,Cód. Produto,Qtd. Produzida,Qtd. Refugada,Qtd. Retrabalhada,Fator Un.,Cód. Un.,Descrição da massa (Composto),Consumo de massa no item em (Kg/100pçs),Manutencao,Qtd. Produzida Acumulada Total,Qtd. Refugada Acumulada Total,Qtd. Retrabalhada Acumulada Total,Fator Un. Acumulado Total,Consumo de massa no item em (Kg/100pçs) Acumulado Total
0,2680830,IJ-044,SA08395,868,21,0,3,PC,N-142/67,8.607,279,868,21,0,3,8.607
1,2680830,IJ-044,SA08395,1014,15,0,4,PC,N-142/67,9.157,278,1882,36,0,7,17.764
2,2680534,IJ-044,SA07321,802,46,0,3,PC,N148/18,4.350,277,2684,82,0,10,22.114
3,2680534,IJ-044,SA07321,907,18,0,3,PC,N148/18,5.700,276,3591,100,0,13,27.814
4,2680830,IJ-044,SA08395,1033,16,0,5,PC,N-142/67,12.407,275,4624,116,0,18,40.221
5,2680830,IJ-044,SA08395,163,1,0,1,PC,N-142/67,2.869,273,4787,117,0,19,43.090
6,2680830,IJ-044,SA08395,753,16,0,4,PC,N-142/67,8.918,272,5540,133,0,23,52.008
7,2682010,IJ-044,SA01801,790,33,0,4,PC,N146/9,9.940,271,6330,166,0,27,61.948
8,2680332,IJ-044,SA02941,310,13,0,3,PC,N148/18,10.140,270,6640,179,0,30,72.088
9,2680332,IJ-044,SA02941,749,15,0,3,PC,N148/18,10.140,269,7389,194,0,33,82.228
10,2680332,IJ-044,SA02941,89,3,0,1,PC,N148/18,3.380,268,7478,197,0,34,85.608
11,2680332,IJ-044,SA02941,723,10,0,3,PC,N148/18,10.140,261,8201,207,0,37,95.748
12,2680332,IJ-044,SA02941,138,4,0,1,PC,N148/18,3.380,259,8339,211,0,38,99.128
13,2680332,IJ-044,SA02941,970,18,0,3,PC,N148/18,10.140,258,9309,229,0,41,109.268
14,2680332,IJ-044,SA02941,865,17,0,3,PC,N148/18,10.140,257,10174,246,0,44,119.408
15,2680332,IJ-044,SA02941,875,25,0,3,PC,N148/18,10.140,256,11049,271,0,47,129.548
16,2680332,IJ-044,SA02941,775,10,0,3,PC,N148/18,10.140,255,11824,281,0,50,139.688
17,2680332,IJ-044,SA02941,789,14,0,3,PC,N148/18,10.140,254,12613,295,0,53,149.828
18,2680332,IJ-044,SA02941,176,3,0,2,PC,N148/18,6.760,252,12789,298,0,55,156.588
19,2683450,IJ-044,SA02941,1067,12,0,5,PC,N148/18,16.674,251,13856,310,0,60,173.262
20,2683569,IJ-044,11974,758,21,0,3,PC,N-158/3,9.462,250,14614,331,0,63,182.724
21,2683666,IJ-044,SA07321,346,6,0,3,PC,N148/18,6.954,249,14960,337,0,66,189.678
22,2682511,IJ-044,SA04416,498,20,0,3,PC,P212/1,8.843,248,15458,357,0,69,198.521
23,2682511,IJ-044,SA04416,240,2,0,2,PC,P212/1,10.086,247,15698,359,0,71,208.607
24,2682511,IJ-044,SA04416,268,2,0,3,PC,P212/1,15.129,246,15966,361,0,74,223.736
25,2682511,IJ-044,SA04416,590,12,0,3,PC,P212/1,15.129,244,16556,373,0,77,238.865
26,2682511,IJ-044,SA04416,614,10,0,3,PC,P212/1,15.129,243,17170,383,0,80,253.994
27,2682511,IJ-044,SA04416,704,7,0,3,PC,P212/1,15.129,242,17874,390,0,83,269.123
28,2682511,IJ-044,SA04416,784,5,0,3,PC,P212/1,15.129,241,18658,395,0,86,284.252
29,2682511,IJ-044,SA04416,674,9,0,3,PC,P212/1,15.129,240,19332,404,0,89,299.381
30,2682511,IJ-044,SA04416,93,0,0,1,PC,P212/1,5.043,239,19425,404,0,90,304.424
31,2684278,IJ-044,SA11684,663,42,0,6,PC,N148/18,11.293,237,20088,446,0,96,315.717
32,2684451,IJ-044,SA02938,702,11,0,4,PC,N-142/67,10.200,236,20790,457,0,100,325.917
33,2684451,IJ-044,SA02938,657,7,0,3,PC,N-142/67,7.650,235,21447,464,0,103,333.567
34,2684451,IJ-044,SA02938,684,18,0,3,PC,N-142/67,7.650,234,22131,482,0,106,341.217
35,2684656,IJ-044,SA00436,709,14,0,3,PC,N-142/67,6.106,233,22840,496,0,109,347.323
36,2684656,IJ-044,SA00436,646,34,0,4,PC,N-142/67,4.024,230,23486,530,0,113,351.347
37,2684656,IJ-044,SA00436,377,19,0,2,PC,N-142/67,2.012,229,23863,549,0,115,353.359
38,2684656,IJ-044,SA00436,343,0,0,2,PC,N-142/67,2.012,228,24206,549,0,117,355.371
39,2684656,IJ-044,SA00436,1017,8,0,3,PC,N-142/67,3.018,226,25223,557,0,120,358.389
40,2684656,IJ-044,SA00436,34,5,0,1,PC,N-142/67,1.006,224,25257,562,0,121,359.395
41,2684451,IJ-044,SA02938,1050,10,0,4,PC,N-142/67,7.112,223,26307,572,0,125,366.507
42,2684451,IJ-044,SA02938,787,18,0,3,PC,N-142/67,7.650,222,27094,590,0,128,374.157
43,2684451,IJ-044,SA02938,319,2,0,3,PC,N-142/67,3.892,221,27413,592,0,131,378.049
44,2685583,IJ-044,SA18476,618,5,0,5,PC,N-142/67,2.618,220,28031,597,0,136,380.667
45,2685583,IJ-044,SA18476,675,16,0,5,PC,N-142/67,7.191,219,28706,613,0,141,387.858
46,2685610,IJ-044,SA01974,57,8,0,1,PC,N148/18,2.820,217,28763,621,0,142,390.678
47,2685610,IJ-044,SA01974,755,11,0,3,PC,N148/18,8.460,216,29518,632,0,145,399.138
48,2685610,IJ-044,SA01974,731,14,0,3,PC,N148/18,8.460,215,30249,646,0,148,407.598
49,2685610,IJ-044,SA01974,930,1,0,3,PC,N148/18,8.460,214,31179,647,0,151,416.058
50,2685803,IJ-044,SA02910,1070,22,0,3,PC,N148/18,1.860,213,32249,669,0,154,417.918
51,2685767,IJ-044,SA03682,763,19,0,3,PC,N148/18,18.000,212,33012,688,0,157,435.918
52,2685767,IJ-044,SA03682,619,11,0,3,PC,N148/18,18.000,209,33631,699,0,160,453.918
53,2685767,IJ-044,SA03682,800,10,0,4,PC,N148/18,17.100,208,34431,709,0,164,471.018
54,2684451,IJ-044,SA02938,1017,13,0,4,PC,N-142/67,10.200,207,35448,722,0,168,481.218
55,2684451,IJ-044,SA02938,402,6,0,2,PC,N-142/67,5.100,202,35850,728,0,170,486.318
56,2684451,IJ-044,SA02938,810,9,0,3,PC,N-142/67,7.650,201,36660,737,0,173,493.968
57,2684451,IJ-044,SA02938,475,17,0,8,PC,N-142/67,37.851,200,37135,754,0,181,531.819
58,2686201,IJ-044,SA04416,633,16,0,3,PC,P212/1,15.129,199,37768,770,0,184,546.948
59,2686201,IJ-044,SA04416,617,15,0,5,PC,P212/1,25.215,198,38385,785,0,189,572.163
60,2686201,IJ-044,SA04416,481,14,0,3,PC,P212/1,15.129,197,38866,799,0,192,587.292
61,2686201,IJ-044,SA04416,86,7,0,1,PC,P212/1,5.043,196,38952,806,0,193,592.335
62,2686201,IJ-044,SA04416,665,8,0,3,PC,P212/1,15.129,195,39617,814,0,196,607.464
63,2686201,IJ-044,SA04416,697,5,0,3,PC,P212/1,15.129,194,40314,819,0,199,622.593
64,2686201,IJ-044,SA04416,281,0,0,2,PC,P212/1,10.086,193,40595,819,0,201,632.679
65,2686201,IJ-044,SA04416,801,9,0,3,PC,P212/1,15.129,192,41396,828,0,204,647.808
66,2686201,IJ-044,SA04416,780,3,0,3,PC,P212/1,15.129,191,42176,831,0,207,662.937
67,2686201,IJ-044,SA04416,2,0,0,1,PC,P212/1,5.043,189,42178,831,0,208,667.980
68,2686773,IJ-044,SA07337,229,21,0,3,PC,F420/306,22.509,188,42407,852,0,211,690.489
69,2686773,IJ-044,SA07337,420,16,0,3,PC,F420/306,26.199,187,42827,868,0,214,716.688
70,2686773,IJ-044,SA07337,718,11,0,3,PC,F420/306,26.199,186,43545,879,0,217,742.887
71,2686201,IJ-044,SA04416,496,25,0,4,PC,P212/1,23.862,185,44041,904,0,221,766.749
72,2686201,IJ-044,SA04416,863,1,0,3,PC,P212/1,15.129,184,44904,905,0,224,781.878
73,2686201,IJ-044,SA04416,564,6,0,2,PC,P212/1,10.086,183,45468,911,0,226,791.964
74,2686201,IJ-044,SA04416,145,2,0,1,PC,P212/1,5.043,182,45613,913,0,227,797.007
75,2686201,IJ-044,SA04416,869,5,0,3,PC,P212/1,15.129,181,46482,918,0,230,812.136
76,2686201,IJ-044,SA04416,706,3,0,3,PC,P212/1,15.129,180,47188,921,0,233,827.265
77,2686201,IJ-044,SA04416,873,8,0,3,PC,P212/1,15.129,179,48061,929,0,236,842.394
78,2686201,IJ-044,SA04416,868,1,0,3,PC,P212/1,15.129,178,48929,930,0,239,857.523
79,2686201,IJ-044,SA04416,813,10,0,3,PC,P212/1,22.589,177,49742,940,0,242,880.112
80,2687844,IJ-044,SA04417,330,7,0,2,PC,F420/306,17.546,174,50072,947,0,244,897.658
81,2687845,IJ-044,SA04416,1382,5,0,2,PC,P212/1,10.086,173,51454,952,0,246,907.744
82,2687845,IJ-044,SA04416,665,3,0,3,PC,P212/1,15.129,172,52119,955,0,249,922.873
83,2687845,IJ-044,SA04416,871,4,0,3,PC,P212/1,15.129,171,52990,959,0,252,938.002
84,2687845,IJ-044,SA04416,717,4,0,3,PC,P212/1,15.129,170,53707,963,0,255,953.131
85,2686826,IJ-044,SA02583,149,1,0,1,PC,F403/32,6.760,168,53856,964,0,256,959.891
86,2686826,IJ-044,SA02583,58,0,0,2,PC,F403/32,11.803,167,53914,964,0,258,971.694
87,2686826,IJ-044,SA02583,22,0,0,1,PC,F403/32,6.760,166,53936,964,0,259,978.454
88,2686826,IJ-044,SA02583,26,0,0,2,PC,F403/32,13.520,165,53962,964,0,261,991.974
89,2686826,IJ-044,SA02583,21,0,0,2,PC,F403/32,13.520,164,53983,964,0,263,1005.494
90,2689104,IJ-044,SA04416,58,20,0,3,PC,P212/1,15.129,163,54041,984,0,266,1020.623
91,2689104,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,161,54042,984,0,267,1025.666
92,2689104,IJ-044,SA04416,718,22,0,3,PC,P212/1,15.129,160,54760,1006,0,270,1040.795
93,2689104,IJ-044,SA04416,414,26,0,3,PC,P212/1,15.129,159,55174,1032,0,273,1055.924
94,2689104,IJ-044,SA04416,556,4,0,3,PC,P212/1,15.129,158,55730,1036,0,276,1071.053
95,2689104,IJ-044,SA04416,25,0,0,2,PC,P212/1,10.086,157,55755,1036,0,278,1081.139
96,2689149,IJ-044,SA07337,45,0,0,2,PC,F420/306,17.466,156,55800,1036,0,280,1098.605
97,2689149,IJ-044,SA07337,258,18,0,2,PC,F420/306,17.466,152,56058,1054,0,282,1116.071
98,2689149,IJ-044,SA07337,423,13,0,3,PC,F420/306,26.199,151,56481,1067,0,285,1142.270
99,2689149,IJ-044,SA07337,720,7,0,4,PC,F420/306,34.932,150,57201,1074,0,289,1177.202
100,2689149,IJ-044,SA07337,510,13,0,3,PC,F420/306,26.199,149,57711,1087,0,292,1203.401
101,2689149,IJ-044,SA07337,177,0,0,1,PC,F420/306,8.733,148,57888,1087,0,293,1212.134
102,2689149,IJ-044,SA07337,3,0,0,1,PC,F420/306,8.733,146,57891,1087,0,294,1220.867
103,2689592,IJ-044,SA04417,544,28,0,4,PC,F420/306,35.052,145,58435,1115,0,298,1255.919
104,2689592,IJ-044,SA04417,561,21,0,4,PC,F420/306,35.092,144,58996,1136,0,302,1291.011
105,2689592,IJ-044,SA04417,480,16,0,3,PC,F420/306,26.319,143,59476,1152,0,305,1317.330
106,2689592,IJ-044,SA04417,496,0,0,4,PC,F420/306,27.632,142,59972,1152,0,309,1344.962
107,2690225,IJ-044,SA04416,551,14,0,3,PC,P212/1,15.129,141,60523,1166,0,312,1360.091
108,2690225,IJ-044,SA04416,122,1,0,1,PC,P212/1,5.043,140,60645,1167,0,313,1365.134
109,2690225,IJ-044,SA04416,798,16,0,3,PC,P212/1,15.129,139,61443,1183,0,316,1380.263
110,2690225,IJ-044,SA04416,878,12,0,3,PC,P212/1,15.129,138,62321,1195,0,319,1395.392
111,2690225,IJ-044,SA04416,815,10,0,3,PC,P212/1,15.129,137,63136,1205,0,322,1410.521
112,2690225,IJ-044,SA04416,795,6,0,3,PC,P212/1,15.129,136,63931,1211,0,325,1425.650
113,2690225,IJ-044,SA04416,802,7,0,4,PC,P212/1,20.172,135,64733,1218,0,329,1445.822
114,2690225,IJ-044,SA04416,543,4,0,2,PC,P212/1,10.086,134,65276,1222,0,331,1455.908
115,2690093,IJ-044,SA02900,43,28,0,1,PC,F420/306,2.616,133,65319,1250,0,332,1458.524
116,2690093,IJ-044,SA02900,635,61,0,3,PC,F420/306,7.848,132,65954,1311,0,335,1466.372
117,2690093,IJ-044,SA02900,708,61,0,3,PC,F420/306,7.848,131,66662,1372,0,338,1474.220
118,2690093,IJ-044,SA02900,583,8,0,3,PC,F420/306,11.992,130,67245,1380,0,341,1486.212
119,2690434,IJ-044,SA07337,252,0,0,3,PC,F420/306,24.226,129,67497,1380,0,344,1510.438
120,2690434,IJ-044,SA07337,428,10,0,2,PC,F420/306,17.466,128,67925,1390,0,346,1527.904
121,2690434,IJ-044,SA07337,216,0,0,1,PC,F420/306,8.733,127,68141,1390,0,347,1536.637
122,2690434,IJ-044,SA07337,95,18,0,1,PC,F420/306,8.733,126,68236,1408,0,348,1545.370
123,2690434,IJ-044,SA07337,657,19,0,3,PC,F420/306,26.199,125,68893,1427,0,351,1571.569
124,2690140,IJ-044,SA07339,465,10,0,3,PC,F420/306,24.055,124,69358,1437,0,354,1595.624
125,2690140,IJ-044,SA07339,600,26,0,3,PC,F420/306,19.767,123,69958,1463,0,357,1615.391
126,2690140,IJ-044,SA07339,792,10,0,3,PC,F420/306,19.767,122,70750,1473,0,360,1635.158
127,2690140,IJ-044,SA07339,110,2,0,1,PC,F420/306,6.589,121,70860,1475,0,361,1641.747
128,2690140,IJ-044,SA07339,2,0,0,1,PC,F420/306,6.589,119,70862,1475,0,362,1648.336
129,2690225,IJ-044,SA04416,502,7,0,3,PC,P212/1,16.675,118,71364,1482,0,365,1665.011
130,2690225,IJ-044,SA04416,780,18,0,3,PC,P212/1,15.129,117,72144,1500,0,368,1680.140
131,2690225,IJ-044,SA04416,799,8,0,3,PC,P212/1,15.129,116,72943,1508,0,371,1695.269
132,2690225,IJ-044,SA04416,818,6,0,3,PC,P212/1,15.129,115,73761,1514,0,374,1710.398
133,2690225,IJ-044,SA04416,341,1,0,2,PC,P212/1,8.317,114,74102,1515,0,376,1718.715
134,2691658,IJ-044,SA02619,74,15,0,1,PC,F420/96,3.274,112,74176,1530,0,377,1721.989
135,2690225,IJ-044,SA04416,291,23,0,3,PC,P212/1,13.360,111,74467,1553,0,380,1735.349
136,2690225,IJ-044,SA04416,764,11,0,3,PC,P212/1,15.129,110,75231,1564,0,383,1750.478
137,2690225,IJ-044,SA04416,651,13,0,3,PC,P212/1,15.129,109,75882,1577,0,386,1765.607
138,2690225,IJ-044,SA04416,753,9,0,3,PC,P212/1,15.129,108,76635,1586,0,389,1780.736
139,2690225,IJ-044,SA04416,190,4,0,1,PC,P212/1,5.043,107,76825,1590,0,390,1785.779
140,2690225,IJ-044,SA04416,241,13,0,2,PC,P212/1,10.086,103,77066,1603,0,392,1795.865
141,2690225,IJ-044,SA04416,801,11,0,3,PC,P212/1,15.129,102,77867,1614,0,395,1810.994
142,2690225,IJ-044,SA04416,811,14,0,3,PC,P212/1,15.129,101,78678,1628,0,398,1826.123
143,2690225,IJ-044,SA04416,804,4,0,3,PC,P212/1,15.129,100,79482,1632,0,401,1841.252
144,2690225,IJ-044,SA04416,246,7,0,1,PC,P212/1,5.043,99,79728,1639,0,402,1846.295
145,2690225,IJ-044,SA04416,148,0,0,1,PC,P212/1,5.043,98,79876,1639,0,403,1851.338
146,2690225,IJ-044,SA04416,375,32,0,2,PC,P212/1,10.086,97,80251,1671,0,405,1861.424
147,2690225,IJ-044,SA04416,13,0,0,1,PC,P212/1,5.043,95,80264,1671,0,406,1866.467
148,2691658,IJ-044,SA02619,304,20,0,2,PC,F420/96,6.548,93,80568,1691,0,408,1873.015
149,2691658,IJ-044,SA02619,130,0,0,1,PC,F420/96,3.274,91,80698,1691,0,409,1876.289
150,2691334,IJ-044,SA04416,299,62,0,4,PC,P212/1,16.634,90,80997,1753,0,413,1892.923
151,2691334,IJ-044,SA04416,162,14,0,1,PC,P212/1,5.043,89,81159,1767,0,414,1897.966
152,2692988,IJ-044,SA07291,40,50,0,1,PC,F403/32,3.500,88,81199,1817,0,415,1901.466
153,2692988,IJ-044,SA07291,5,16,0,1,PC,F403/32,3.500,87,81204,1833,0,416,1904.966
154,2693639,IJ-044,SA04416,302,16,0,2,PC,P212/1,10.086,81,81506,1849,0,418,1915.052
155,2693639,IJ-044,SA04416,421,17,0,3,PC,P212/1,15.129,80,81927,1866,0,421,1930.181
156,2693639,IJ-044,SA04416,624,26,0,3,PC,P212/1,15.129,79,82551,1892,0,424,1945.310
157,2693639,IJ-044,SA04416,258,2,0,1,PC,P212/1,5.043,78,82809,1894,0,425,1950.353
158,2693639,IJ-044,SA04416,155,0,0,1,PC,P212/1,5.043,77,82964,1894,0,426,1955.396
159,2693639,IJ-044,SA04416,762,23,0,3,PC,P212/1,15.129,76,83726,1917,0,429,1970.525
160,2693639,IJ-044,SA04416,768,13,0,3,PC,P212/1,15.129,75,84494,1930,0,432,1985.654
161,2693639,IJ-044,SA04416,609,9,0,3,PC,P212/1,15.129,74,85103,1939,0,435,2000.783
162,2693639,IJ-044,SA04416,595,9,0,3,PC,P212/1,15.129,73,85698,1948,0,438,2015.912
163,2693639,IJ-044,SA04416,618,8,0,2,PC,P212/1,10.086,72,86316,1956,0,440,2025.998
164,2693639,IJ-044,SA04416,128,5,0,1,PC,P212/1,5.043,70,86444,1961,0,441,2031.041
165,2693639,IJ-044,SA04416,670,18,0,3,PC,P212/1,15.129,69,87114,1979,0,444,2046.170
166,2693639,IJ-044,SA04416,36,0,0,1,PC,P212/1,5.043,68,87150,1979,0,445,2051.213
167,2693639,IJ-044,SA04416,561,7,0,3,PC,P212/1,15.129,67,87711,1986,0,448,2066.342
168,2693639,IJ-044,SA04416,508,1,0,3,PC,P212/1,15.129,66,88219,1987,0,451,2081.471
169,2693639,IJ-044,SA04416,732,2,0,4,PC,P212/1,20.172,65,88951,1989,0,455,2101.643
170,2693639,IJ-044,SA04416,88,0,0,1,PC,P212/1,5.043,64,89039,1989,0,456,2106.686
171,2693639,IJ-044,SA04416,814,5,0,3,PC,P212/1,15.129,62,89853,1994,0,459,2121.815
172,2693639,IJ-044,SA04416,482,0,0,2,PC,P212/1,10.086,61,90335,1994,0,461,2131.901
173,2693639,IJ-044,SA04416,463,24,0,3,PC,P212/1,15.129,60,90798,2018,0,464,2147.030
174,2693639,IJ-044,SA04416,777,19,0,3,PC,P212/1,15.129,59,91575,2037,0,467,2162.159
175,2693639,IJ-044,SA04416,535,6,0,3,PC,P212/1,15.129,58,92110,2043,0,470,2177.288
176,2693639,IJ-044,SA04416,260,12,0,1,PC,P212/1,5.043,57,92370,2055,0,471,2182.331
177,2693639,IJ-044,SA04416,118,3,0,1,PC,P212/1,5.043,56,92488,2058,0,472,2187.374
178,2693639,IJ-044,SA04416,822,6,0,3,PC,P212/1,15.129,55,93310,2064,0,475,2202.503
179,2694422,IJ-044,SA02973,269,12,0,3,PC,F403/32,10.843,54,93579,2076,0,478,2213.346
180,2694422,IJ-044,SA02973,470,7,0,3,PC,F403/32,8.700,53,94049,2083,0,481,2222.046
181,2694422,IJ-044,SA02973,500,43,0,3,PC,F403/32,8.700,52,94549,2126,0,484,2230.746
182,2694422,IJ-044,SA02973,742,12,0,3,PC,F403/32,8.700,51,95291,2138,0,487,2239.446
183,2694422,IJ-044,SA02973,1,0,0,1,PC,F403/32,2.900,49,95292,2138,0,488,2242.346
184,2694422,IJ-044,SA02973,821,7,0,3,PC,F403/32,8.700,48,96113,2145,0,491,2251.046
185,2695553,IJ-044,SA15829,354,19,0,3,PC,F420/191,7.450,47,96467,2164,0,494,2258.496
186,2695553,IJ-044,SA15829,777,46,0,3,PC,F420/191,6.825,46,97244,2210,0,497,2265.321
187,2695553,IJ-044,SA15829,825,29,0,3,PC,F420/191,6.825,45,98069,2239,0,500,2272.146
188,2695553,IJ-044,SA15829,534,42,0,4,PC,F420/191,9.100,44,98603,2281,0,504,2281.246
189,2695553,IJ-044,SA15829,249,5,0,1,PC,F420/191,2.275,43,98852,2286,0,505,2283.521
190,2695553,IJ-044,SA15829,120,0,0,1,PC,F420/191,2.275,42,98972,2286,0,506,2285.796
191,2695455,IJ-044,SA07337,678,20,0,3,PC,F420/306,19.741,41,99650,2306,0,509,2305.537
192,2695455,IJ-044,SA07337,567,32,0,3,PC,F420/306,26.199,40,100217,2338,0,512,2331.736
193,2695455,IJ-044,SA07337,505,40,0,3,PC,F420/306,26.199,39,100722,2378,0,515,2357.935
194,2695455,IJ-044,SA07337,485,25,0,2,PC,F420/306,17.466,38,101207,2403,0,517,2375.401
195,2695455,IJ-044,SA07337,500,21,0,3,PC,F420/306,26.199,37,101707,2424,0,520,2401.600
196,2695455,IJ-044,SA07337,477,2,0,2,PC,F420/306,17.466,36,102184,2426,0,522,2419.066
197,2695455,IJ-044,SA07337,100,4,0,1,PC,F420/306,8.733,35,102284,2430,0,523,2427.799
198,2695455,IJ-044,SA07337,765,14,0,3,PC,F420/306,26.199,34,103049,2444,0,526,2453.998
199,2695455,IJ-044,SA07337,676,10,0,3,PC,F420/306,26.199,33,103725,2454,0,529,2480.197
200,2695085,IJ-044,SA04416,671,29,0,4,PC,P212/1,23.862,32,104396,2483,0,533,2504.059
201,2695085,IJ-044,SA04416,852,7,0,3,PC,P212/1,15.129,31,105248,2490,0,536,2519.188
202,2695085,IJ-044,SA04416,833,2,0,3,PC,P212/1,15.129,30,106081,2492,0,539,2534.317
203,2695085,IJ-044,SA04416,135,3,0,1,PC,P212/1,5.043,28,106216,2495,0,540,2539.360
204,2695085,IJ-044,SA04416,842,9,0,3,PC,P212/1,15.129,27,107058,2504,0,543,2554.489
205,2695085,IJ-044,SA04416,840,6,0,3,PC,P212/1,15.129,26,107898,2510,0,546,2569.618
206,2695085,IJ-044,SA04416,3,0,0,1,PC,P212/1,5.043,25,107901,2510,0,547,2574.661
207,2695085,IJ-044,SA04416,797,20,0,3,PC,P212/1,15.129,24,108698,2530,0,550,2589.790
208,2695085,IJ-044,SA04416,603,10,0,2,PC,P212/1,10.086,23,109301,2540,0,552,2599.876
209,2695085,IJ-044,SA04416,3,0,0,1,PC,P212/1,5.043,21,109304,2540,0,553,2604.919
210,2695085,IJ-044,SA04416,542,18,0,3,PC,P212/1,15.129,20,109846,2558,0,556,2620.048
211,2695085,IJ-044,SA04416,664,11,0,4,PC,P212/1,23.264,19,110510,2569,0,560,2643.312
212,2695456,IJ-044,SA07339,763,7,0,3,PC,F420/306,19.767,18,111273,2576,0,563,2663.079
213,2695456,IJ-044,SA07339,685,6,0,3,PC,F420/306,19.767,17,111958,2582,0,566,2682.846
214,2697109,IJ-044,SA04416,754,11,0,6,PC,P212/1,34.896,16,112712,2593,0,572,2717.742
215,2697109,IJ-044,SA04416,274,4,0,1,PC,P212/1,5.043,15,112986,2597,0,573,2722.785
216,2697109,IJ-044,SA04416,139,6,0,1,PC,P212/1,5.043,14,113125,2603,0,574,2727.828
217,2697109,IJ-044,SA04416,185,3,0,2,PC,P212/1,10.086,13,113310,2606,0,576,2737.914
218,2697109,IJ-044,SA04416,837,10,0,3,PC,P212/1,15.129,12,114147,2616,0,579,2753.043
219,2697109,IJ-044,SA04416,782,19,0,3,PC,P212/1,15.129,11,114929,2635,0,582,2768.172
220,2697109,IJ-044,SA04416,607,9,0,3,PC,P212/1,15.129,10,115536,2644,0,585,2783.301
221,2697109,IJ-044,SA04416,535,11,0,2,PC,P212/1,10.086,9,116071,2655,0,587,2793.387
222,2697563,IJ-044,SA07371,128,1,0,3,PC,F424/85,21.000,8,116199,2656,0,590,2814.387
223,2697563,IJ-044,SA07371,474,17,0,3,PC,F424/85,21.000,6,116673,2673,0,593,2835.387
224,2697563,IJ-044,SA07371,421,6,0,3,PC,F424/85,21.000,5,117094,2679,0,596,2856.387
225,2697563,IJ-044,SA07371,585,20,0,4,PC,F424/85,28.000,4,117679,2699,0,600,2884.387
226,2697563,IJ-044,SA07371,618,9,0,3,PC,F424/85,21.000,3,118297,2708,0,603,2905.387
227,2697563,IJ-044,SA07371,492,11,0,4,PC,F424/85,28.000,2,118789,2719,0,607,2933.387
228,2697563,IJ-044,SA07371,412,0,0,2,PC,F424/85,14.000,1,119201,2719,0,609,2947.387
229,2697563,IJ-044,SA07371,114,4,0,1,PC,F424/85,7.000,0,119315,2723,0,610,2954.387

In [19]:
# Get the list of columns
cols = df_result.columns.tolist()

# Remove 'Manutencao' from the list
cols.remove("Manutencao")

# Append 'Manutencao' to the end of the list
cols.append("Manutencao")

In [20]:
cols

['Cód. Ordem',
 'Cód. Recurso',
 'Cód. Produto',
 'Qtd. Produzida',
 'Qtd. Refugada',
 'Qtd. Retrabalhada',
 'Fator Un.',
 'Cód. Un.',
 'Descrição da massa (Composto)',
 'Consumo de massa no item em (Kg/100pçs)',
 'Qtd. Produzida Acumulada Total',
 'Qtd. Refugada Acumulada Total',
 'Qtd. Retrabalhada Acumulada Total',
 'Fator Un. Acumulado Total',
 'Consumo de massa no item em (Kg/100pçs) Acumulado Total',
 'Manutencao']

In [21]:
# Reorder the dataframe with the new column order
df_result = df_result[cols]

In [22]:
df_result

,Cód. Ordem,Cód. Recurso,Cód. Produto,Qtd. Produzida,Qtd. Refugada,Qtd. Retrabalhada,Fator Un.,Cód. Un.,Descrição da massa (Composto),Consumo de massa no item em (Kg/100pçs),Qtd. Produzida Acumulada Total,Qtd. Refugada Acumulada Total,Qtd. Retrabalhada Acumulada Total,Fator Un. Acumulado Total,Consumo de massa no item em (Kg/100pçs) Acumulado Total,Manutencao
0,2680830,IJ-044,SA08395,868,21,0,3,PC,N-142/67,8.607,868,21,0,3,8.607,279
1,2680830,IJ-044,SA08395,1014,15,0,4,PC,N-142/67,9.157,1882,36,0,7,17.764,278
2,2680534,IJ-044,SA07321,802,46,0,3,PC,N148/18,4.350,2684,82,0,10,22.114,277
3,2680534,IJ-044,SA07321,907,18,0,3,PC,N148/18,5.700,3591,100,0,13,27.814,276
4,2680830,IJ-044,SA08395,1033,16,0,5,PC,N-142/67,12.407,4624,116,0,18,40.221,275
5,2680830,IJ-044,SA08395,163,1,0,1,PC,N-142/67,2.869,4787,117,0,19,43.090,273
6,2680830,IJ-044,SA08395,753,16,0,4,PC,N-142/67,8.918,5540,133,0,23,52.008,272
7,2682010,IJ-044,SA01801,790,33,0,4,PC,N146/9,9.940,6330,166,0,27,61.948,271
8,2680332,IJ-044,SA02941,310,13,0,3,PC,N148/18,10.140,6640,179,0,30,72.088,270
9,2680332,IJ-044,SA02941,749,15,0,3,PC,N148/18,10.140,7389,194,0,33,82.228,269
10,2680332,IJ-044,SA02941,89,3,0,1,PC,N148/18,3.380,7478,197,0,34,85.608,268
11,2680332,IJ-044,SA02941,723,10,0,3,PC,N148/18,10.140,8201,207,0,37,95.748,261
12,2680332,IJ-044,SA02941,138,4,0,1,PC,N148/18,3.380,8339,211,0,38,99.128,259
13,2680332,IJ-044,SA02941,970,18,0,3,PC,N148/18,10.140,9309,229,0,41,109.268,258
14,2680332,IJ-044,SA02941,865,17,0,3,PC,N148/18,10.140,10174,246,0,44,119.408,257
15,2680332,IJ-044,SA02941,875,25,0,3,PC,N148/18,10.140,11049,271,0,47,129.548,256
16,2680332,IJ-044,SA02941,775,10,0,3,PC,N148/18,10.140,11824,281,0,50,139.688,255
17,2680332,IJ-044,SA02941,789,14,0,3,PC,N148/18,10.140,12613,295,0,53,149.828,254
18,2680332,IJ-044,SA02941,176,3,0,2,PC,N148/18,6.760,12789,298,0,55,156.588,252
19,2683450,IJ-044,SA02941,1067,12,0,5,PC,N148/18,16.674,13856,310,0,60,173.262,251
20,2683569,IJ-044,11974,758,21,0,3,PC,N-158/3,9.462,14614,331,0,63,182.724,250
21,2683666,IJ-044,SA07321,346,6,0,3,PC,N148/18,6.954,14960,337,0,66,189.678,249
22,2682511,IJ-044,SA04416,498,20,0,3,PC,P212/1,8.843,15458,357,0,69,198.521,248
23,2682511,IJ-044,SA04416,240,2,0,2,PC,P212/1,10.086,15698,359,0,71,208.607,247
24,2682511,IJ-044,SA04416,268,2,0,3,PC,P212/1,15.129,15966,361,0,74,223.736,246
25,2682511,IJ-044,SA04416,590,12,0,3,PC,P212/1,15.129,16556,373,0,77,238.865,244
26,2682511,IJ-044,SA04416,614,10,0,3,PC,P212/1,15.129,17170,383,0,80,253.994,243
27,2682511,IJ-044,SA04416,704,7,0,3,PC,P212/1,15.129,17874,390,0,83,269.123,242
28,2682511,IJ-044,SA04416,784,5,0,3,PC,P212/1,15.129,18658,395,0,86,284.252,241
29,2682511,IJ-044,SA04416,674,9,0,3,PC,P212/1,15.129,19332,404,0,89,299.381,240
30,2682511,IJ-044,SA04416,93,0,0,1,PC,P212/1,5.043,19425,404,0,90,304.424,239
31,2684278,IJ-044,SA11684,663,42,0,6,PC,N148/18,11.293,20088,446,0,96,315.717,237
32,2684451,IJ-044,SA02938,702,11,0,4,PC,N-142/67,10.200,20790,457,0,100,325.917,236
33,2684451,IJ-044,SA02938,657,7,0,3,PC,N-142/67,7.650,21447,464,0,103,333.567,235
34,2684451,IJ-044,SA02938,684,18,0,3,PC,N-142/67,7.650,22131,482,0,106,341.217,234
35,2684656,IJ-044,SA00436,709,14,0,3,PC,N-142/67,6.106,22840,496,0,109,347.323,233
36,2684656,IJ-044,SA00436,646,34,0,4,PC,N-142/67,4.024,23486,530,0,113,351.347,230
37,2684656,IJ-044,SA00436,377,19,0,2,PC,N-142/67,2.012,23863,549,0,115,353.359,229
38,2684656,IJ-044,SA00436,343,0,0,2,PC,N-142/67,2.012,24206,549,0,117,355.371,228
39,2684656,IJ-044,SA00436,1017,8,0,3,PC,N-142/67,3.018,25223,557,0,120,358.389,226
40,2684656,IJ-044,SA00436,34,5,0,1,PC,N-142/67,1.006,25257,562,0,121,359.395,224
41,2684451,IJ-044,SA02938,1050,10,0,4,PC,N-142/67,7.112,26307,572,0,125,366.507,223
42,2684451,IJ-044,SA02938,787,18,0,3,PC,N-142/67,7.650,27094,590,0,128,374.157,222
43,2684451,IJ-044,SA02938,319,2,0,3,PC,N-142/67,3.892,27413,592,0,131,378.049,221
44,2685583,IJ-044,SA18476,618,5,0,5,PC,N-142/67,2.618,28031,597,0,136,380.667,220
45,2685583,IJ-044,SA18476,675,16,0,5,PC,N-142/67,7.191,28706,613,0,141,387.858,219
46,2685610,IJ-044,SA01974,57,8,0,1,PC,N148/18,2.820,28763,621,0,142,390.678,217
47,2685610,IJ-044,SA01974,755,11,0,3,PC,N148/18,8.460,29518,632,0,145,399.138,216
48,2685610,IJ-044,SA01974,731,14,0,3,PC,N148/18,8.460,30249,646,0,148,407.598,215
49,2685610,IJ-044,SA01974,930,1,0,3,PC,N148/18,8.460,31179,647,0,151,416.058,214
50,2685803,IJ-044,SA02910,1070,22,0,3,PC,N148/18,1.860,32249,669,0,154,417.918,213
51,2685767,IJ-044,SA03682,763,19,0,3,PC,N148/18,18.000,33012,688,0,157,435.918,212
52,2685767,IJ-044,SA03682,619,11,0,3,PC,N148/18,18.000,33631,699,0,160,453.918,209
53,2685767,IJ-044,SA03682,800,10,0,4,PC,N148/18,17.100,34431,709,0,164,471.018,208
54,2684451,IJ-044,SA02938,1017,13,0,4,PC,N-142/67,10.200,35448,722,0,168,481.218,207
55,2684451,IJ-044,SA02938,402,6,0,2,PC,N-142/67,5.100,35850,728,0,170,486.318,202
56,2684451,IJ-044,SA02938,810,9,0,3,PC,N-142/67,7.650,36660,737,0,173,493.968,201
57,2684451,IJ-044,SA02938,475,17,0,8,PC,N-142/67,37.851,37135,754,0,181,531.819,200
58,2686201,IJ-044,SA04416,633,16,0,3,PC,P212/1,15.129,37768,770,0,184,546.948,199
59,2686201,IJ-044,SA04416,617,15,0,5,PC,P212/1,25.215,38385,785,0,189,572.163,198
60,2686201,IJ-044,SA04416,481,14,0,3,PC,P212/1,15.129,38866,799,0,192,587.292,197
61,2686201,IJ-044,SA04416,86,7,0,1,PC,P212/1,5.043,38952,806,0,193,592.335,196
62,2686201,IJ-044,SA04416,665,8,0,3,PC,P212/1,15.129,39617,814,0,196,607.464,195
63,2686201,IJ-044,SA04416,697,5,0,3,PC,P212/1,15.129,40314,819,0,199,622.593,194
64,2686201,IJ-044,SA04416,281,0,0,2,PC,P212/1,10.086,40595,819,0,201,632.679,193
65,2686201,IJ-044,SA04416,801,9,0,3,PC,P212/1,15.129,41396,828,0,204,647.808,192
66,2686201,IJ-044,SA04416,780,3,0,3,PC,P212/1,15.129,42176,831,0,207,662.937,191
67,2686201,IJ-044,SA04416,2,0,0,1,PC,P212/1,5.043,42178,831,0,208,667.980,189
68,2686773,IJ-044,SA07337,229,21,0,3,PC,F420/306,22.509,42407,852,0,211,690.489,188
69,2686773,IJ-044,SA07337,420,16,0,3,PC,F420/306,26.199,42827,868,0,214,716.688,187
70,2686773,IJ-044,SA07337,718,11,0,3,PC,F420/306,26.199,43545,879,0,217,742.887,186
71,2686201,IJ-044,SA04416,496,25,0,4,PC,P212/1,23.862,44041,904,0,221,766.749,185
72,2686201,IJ-044,SA04416,863,1,0,3,PC,P212/1,15.129,44904,905,0,224,781.878,184
73,2686201,IJ-044,SA04416,564,6,0,2,PC,P212/1,10.086,45468,911,0,226,791.964,183
74,2686201,IJ-044,SA04416,145,2,0,1,PC,P212/1,5.043,45613,913,0,227,797.007,182
75,2686201,IJ-044,SA04416,869,5,0,3,PC,P212/1,15.129,46482,918,0,230,812.136,181
76,2686201,IJ-044,SA04416,706,3,0,3,PC,P212/1,15.129,47188,921,0,233,827.265,180
77,2686201,IJ-044,SA04416,873,8,0,3,PC,P212/1,15.129,48061,929,0,236,842.394,179
78,2686201,IJ-044,SA04416,868,1,0,3,PC,P212/1,15.129,48929,930,0,239,857.523,178
79,2686201,IJ-044,SA04416,813,10,0,3,PC,P212/1,22.589,49742,940,0,242,880.112,177
80,2687844,IJ-044,SA04417,330,7,0,2,PC,F420/306,17.546,50072,947,0,244,897.658,174
81,2687845,IJ-044,SA04416,1382,5,0,2,PC,P212/1,10.086,51454,952,0,246,907.744,173
82,2687845,IJ-044,SA04416,665,3,0,3,PC,P212/1,15.129,52119,955,0,249,922.873,172
83,2687845,IJ-044,SA04416,871,4,0,3,PC,P212/1,15.129,52990,959,0,252,938.002,171
84,2687845,IJ-044,SA04416,717,4,0,3,PC,P212/1,15.129,53707,963,0,255,953.131,170
85,2686826,IJ-044,SA02583,149,1,0,1,PC,F403/32,6.760,53856,964,0,256,959.891,168
86,2686826,IJ-044,SA02583,58,0,0,2,PC,F403/32,11.803,53914,964,0,258,971.694,167
87,2686826,IJ-044,SA02583,22,0,0,1,PC,F403/32,6.760,53936,964,0,259,978.454,166
88,2686826,IJ-044,SA02583,26,0,0,2,PC,F403/32,13.520,53962,964,0,261,991.974,165
89,2686826,IJ-044,SA02583,21,0,0,2,PC,F403/32,13.520,53983,964,0,263,1005.494,164
90,2689104,IJ-044,SA04416,58,20,0,3,PC,P212/1,15.129,54041,984,0,266,1020.623,163
91,2689104,IJ-044,SA04416,1,0,0,1,PC,P212/1,5.043,54042,984,0,267,1025.666,161
92,2689104,IJ-044,SA04416,718,22,0,3,PC,P212/1,15.129,54760,1006,0,270,1040.795,160
93,2689104,IJ-044,SA04416,414,26,0,3,PC,P212/1,15.129,55174,1032,0,273,1055.924,159
94,2689104,IJ-044,SA04416,556,4,0,3,PC,P212/1,15.129,55730,1036,0,276,1071.053,158
95,2689104,IJ-044,SA04416,25,0,0,2,PC,P212/1,10.086,55755,1036,0,278,1081.139,157
96,2689149,IJ-044,SA07337,45,0,0,2,PC,F420/306,17.466,55800,1036,0,280,1098.605,156
97,2689149,IJ-044,SA07337,258,18,0,2,PC,F420/306,17.466,56058,1054,0,282,1116.071,152
98,2689149,IJ-044,SA07337,423,13,0,3,PC,F420/306,26.199,56481,1067,0,285,1142.270,151
99,2689149,IJ-044,SA07337,720,7,0,4,PC,F420/306,34.932,57201,1074,0,289,1177.202,150
100,2689149,IJ-044,SA07337,510,13,0,3,PC,F420/306,26.199,57711,1087,0,292,1203.401,149
101,2689149,IJ-044,SA07337,177,0,0,1,PC,F420/306,8.733,57888,1087,0,293,1212.134,148
102,2689149,IJ-044,SA07337,3,0,0,1,PC,F420/306,8.733,57891,1087,0,294,1220.867,146
103,2689592,IJ-044,SA04417,544,28,0,4,PC,F420/306,35.052,58435,1115,0,298,1255.919,145
104,2689592,IJ-044,SA04417,561,21,0,4,PC,F420/306,35.092,58996,1136,0,302,1291.011,144
105,2689592,IJ-044,SA04417,480,16,0,3,PC,F420/306,26.319,59476,1152,0,305,1317.330,143
106,2689592,IJ-044,SA04417,496,0,0,4,PC,F420/306,27.632,59972,1152,0,309,1344.962,142
107,2690225,IJ-044,SA04416,551,14,0,3,PC,P212/1,15.129,60523,1166,0,312,1360.091,141
108,2690225,IJ-044,SA04416,122,1,0,1,PC,P212/1,5.043,60645,1167,0,313,1365.134,140
109,2690225,IJ-044,SA04416,798,16,0,3,PC,P212/1,15.129,61443,1183,0,316,1380.263,139
110,2690225,IJ-044,SA04416,878,12,0,3,PC,P212/1,15.129,62321,1195,0,319,1395.392,138
111,2690225,IJ-044,SA04416,815,10,0,3,PC,P212/1,15.129,63136,1205,0,322,1410.521,137
112,2690225,IJ-044,SA04416,795,6,0,3,PC,P212/1,15.129,63931,1211,0,325,1425.650,136
113,2690225,IJ-044,SA04416,802,7,0,4,PC,P212/1,20.172,64733,1218,0,329,1445.822,135
114,2690225,IJ-044,SA04416,543,4,0,2,PC,P212/1,10.086,65276,1222,0,331,1455.908,134
115,2690093,IJ-044,SA02900,43,28,0,1,PC,F420/306,2.616,65319,1250,0,332,1458.524,133
116,2690093,IJ-044,SA02900,635,61,0,3,PC,F420/306,7.848,65954,1311,0,335,1466.372,132
117,2690093,IJ-044,SA02900,708,61,0,3,PC,F420/306,7.848,66662,1372,0,338,1474.220,131
118,2690093,IJ-044,SA02900,583,8,0,3,PC,F420/306,11.992,67245,1380,0,341,1486.212,130
119,2690434,IJ-044,SA07337,252,0,0,3,PC,F420/306,24.226,67497,1380,0,344,1510.438,129
120,2690434,IJ-044,SA07337,428,10,0,2,PC,F420/306,17.466,67925,1390,0,346,1527.904,128
121,2690434,IJ-044,SA07337,216,0,0,1,PC,F420/306,8.733,68141,1390,0,347,1536.637,127
122,2690434,IJ-044,SA07337,95,18,0,1,PC,F420/306,8.733,68236,1408,0,348,1545.370,126
123,2690434,IJ-044,SA07337,657,19,0,3,PC,F420/306,26.199,68893,1427,0,351,1571.569,125
124,2690140,IJ-044,SA07339,465,10,0,3,PC,F420/306,24.055,69358,1437,0,354,1595.624,124
125,2690140,IJ-044,SA07339,600,26,0,3,PC,F420/306,19.767,69958,1463,0,357,1615.391,123
126,2690140,IJ-044,SA07339,792,10,0,3,PC,F420/306,19.767,70750,1473,0,360,1635.158,122
127,2690140,IJ-044,SA07339,110,2,0,1,PC,F420/306,6.589,70860,1475,0,361,1641.747,121
128,2690140,IJ-044,SA07339,2,0,0,1,PC,F420/306,6.589,70862,1475,0,362,1648.336,119
129,2690225,IJ-044,SA04416,502,7,0,3,PC,P212/1,16.675,71364,1482,0,365,1665.011,118
130,2690225,IJ-044,SA04416,780,18,0,3,PC,P212/1,15.129,72144,1500,0,368,1680.140,117
131,2690225,IJ-044,SA04416,799,8,0,3,PC,P212/1,15.129,72943,1508,0,371,1695.269,116
132,2690225,IJ-044,SA04416,818,6,0,3,PC,P212/1,15.129,73761,1514,0,374,1710.398,115
133,2690225,IJ-044,SA04416,341,1,0,2,PC,P212/1,8.317,74102,1515,0,376,1718.715,114
134,2691658,IJ-044,SA02619,74,15,0,1,PC,F420/96,3.274,74176,1530,0,377,1721.989,112
135,2690225,IJ-044,SA04416,291,23,0,3,PC,P212/1,13.360,74467,1553,0,380,1735.349,111
136,2690225,IJ-044,SA04416,764,11,0,3,PC,P212/1,15.129,75231,1564,0,383,1750.478,110
137,2690225,IJ-044,SA04416,651,13,0,3,PC,P212/1,15.129,75882,1577,0,386,1765.607,109
138,2690225,IJ-044,SA04416,753,9,0,3,PC,P212/1,15.129,76635,1586,0,389,1780.736,108
139,2690225,IJ-044,SA04416,190,4,0,1,PC,P212/1,5.043,76825,1590,0,390,1785.779,107
140,2690225,IJ-044,SA04416,241,13,0,2,PC,P212/1,10.086,77066,1603,0,392,1795.865,103
141,2690225,IJ-044,SA04416,801,11,0,3,PC,P212/1,15.129,77867,1614,0,395,1810.994,102
142,2690225,IJ-044,SA04416,811,14,0,3,PC,P212/1,15.129,78678,1628,0,398,1826.123,101
143,2690225,IJ-044,SA04416,804,4,0,3,PC,P212/1,15.129,79482,1632,0,401,1841.252,100
144,2690225,IJ-044,SA04416,246,7,0,1,PC,P212/1,5.043,79728,1639,0,402,1846.295,99
145,2690225,IJ-044,SA04416,148,0,0,1,PC,P212/1,5.043,79876,1639,0,403,1851.338,98
146,2690225,IJ-044,SA04416,375,32,0,2,PC,P212/1,10.086,80251,1671,0,405,1861.424,97
147,2690225,IJ-044,SA04416,13,0,0,1,PC,P212/1,5.043,80264,1671,0,406,1866.467,95
148,2691658,IJ-044,SA02619,304,20,0,2,PC,F420/96,6.548,80568,1691,0,408,1873.015,93
149,2691658,IJ-044,SA02619,130,0,0,1,PC,F420/96,3.274,80698,1691,0,409,1876.289,91
150,2691334,IJ-044,SA04416,299,62,0,4,PC,P212/1,16.634,80997,1753,0,413,1892.923,90
151,2691334,IJ-044,SA04416,162,14,0,1,PC,P212/1,5.043,81159,1767,0,414,1897.966,89
152,2692988,IJ-044,SA07291,40,50,0,1,PC,F403/32,3.500,81199,1817,0,415,1901.466,88
153,2692988,IJ-044,SA07291,5,16,0,1,PC,F403/32,3.500,81204,1833,0,416,1904.966,87
154,2693639,IJ-044,SA04416,302,16,0,2,PC,P212/1,10.086,81506,1849,0,418,1915.052,81
155,2693639,IJ-044,SA04416,421,17,0,3,PC,P212/1,15.129,81927,1866,0,421,1930.181,80
156,2693639,IJ-044,SA04416,624,26,0,3,PC,P212/1,15.129,82551,1892,0,424,1945.310,79
157,2693639,IJ-044,SA04416,258,2,0,1,PC,P212/1,5.043,82809,1894,0,425,1950.353,78
158,2693639,IJ-044,SA04416,155,0,0,1,PC,P212/1,5.043,82964,1894,0,426,1955.396,77
159,2693639,IJ-044,SA04416,762,23,0,3,PC,P212/1,15.129,83726,1917,0,429,1970.525,76
160,2693639,IJ-044,SA04416,768,13,0,3,PC,P212/1,15.129,84494,1930,0,432,1985.654,75
161,2693639,IJ-044,SA04416,609,9,0,3,PC,P212/1,15.129,85103,1939,0,435,2000.783,74
162,2693639,IJ-044,SA04416,595,9,0,3,PC,P212/1,15.129,85698,1948,0,438,2015.912,73
163,2693639,IJ-044,SA04416,618,8,0,2,PC,P212/1,10.086,86316,1956,0,440,2025.998,72
164,2693639,IJ-044,SA04416,128,5,0,1,PC,P212/1,5.043,86444,1961,0,441,2031.041,70
165,2693639,IJ-044,SA04416,670,18,0,3,PC,P212/1,15.129,87114,1979,0,444,2046.170,69
166,2693639,IJ-044,SA04416,36,0,0,1,PC,P212/1,5.043,87150,1979,0,445,2051.213,68
167,2693639,IJ-044,SA04416,561,7,0,3,PC,P212/1,15.129,87711,1986,0,448,2066.342,67
168,2693639,IJ-044,SA04416,508,1,0,3,PC,P212/1,15.129,88219,1987,0,451,2081.471,66
169,2693639,IJ-044,SA04416,732,2,0,4,PC,P212/1,20.172,88951,1989,0,455,2101.643,65
170,2693639,IJ-044,SA04416,88,0,0,1,PC,P212/1,5.043,89039,1989,0,456,2106.686,64
171,2693639,IJ-044,SA04416,814,5,0,3,PC,P212/1,15.129,89853,1994,0,459,2121.815,62
172,2693639,IJ-044,SA04416,482,0,0,2,PC,P212/1,10.086,90335,1994,0,461,2131.901,61
173,2693639,IJ-044,SA04416,463,24,0,3,PC,P212/1,15.129,90798,2018,0,464,2147.030,60
174,2693639,IJ-044,SA04416,777,19,0,3,PC,P212/1,15.129,91575,2037,0,467,2162.159,59
175,2693639,IJ-044,SA04416,535,6,0,3,PC,P212/1,15.129,92110,2043,0,470,2177.288,58
176,2693639,IJ-044,SA04416,260,12,0,1,PC,P212/1,5.043,92370,2055,0,471,2182.331,57
177,2693639,IJ-044,SA04416,118,3,0,1,PC,P212/1,5.043,92488,2058,0,472,2187.374,56
178,2693639,IJ-044,SA04416,822,6,0,3,PC,P212/1,15.129,93310,2064,0,475,2202.503,55
179,2694422,IJ-044,SA02973,269,12,0,3,PC,F403/32,10.843,93579,2076,0,478,2213.346,54
180,2694422,IJ-044,SA02973,470,7,0,3,PC,F403/32,8.700,94049,2083,0,481,2222.046,53
181,2694422,IJ-044,SA02973,500,43,0,3,PC,F403/32,8.700,94549,2126,0,484,2230.746,52
182,2694422,IJ-044,SA02973,742,12,0,3,PC,F403/32,8.700,95291,2138,0,487,2239.446,51
183,2694422,IJ-044,SA02973,1,0,0,1,PC,F403/32,2.900,95292,2138,0,488,2242.346,49
184,2694422,IJ-044,SA02973,821,7,0,3,PC,F403/32,8.700,96113,2145,0,491,2251.046,48
185,2695553,IJ-044,SA15829,354,19,0,3,PC,F420/191,7.450,96467,2164,0,494,2258.496,47
186,2695553,IJ-044,SA15829,777,46,0,3,PC,F420/191,6.825,97244,2210,0,497,2265.321,46
187,2695553,IJ-044,SA15829,825,29,0,3,PC,F420/191,6.825,98069,2239,0,500,2272.146,45
188,2695553,IJ-044,SA15829,534,42,0,4,PC,F420/191,9.100,98603,2281,0,504,2281.246,44
189,2695553,IJ-044,SA15829,249,5,0,1,PC,F420/191,2.275,98852,2286,0,505,2283.521,43
190,2695553,IJ-044,SA15829,120,0,0,1,PC,F420/191,2.275,98972,2286,0,506,2285.796,42
191,2695455,IJ-044,SA07337,678,20,0,3,PC,F420/306,19.741,99650,2306,0,509,2305.537,41
192,2695455,IJ-044,SA07337,567,32,0,3,PC,F420/306,26.199,100217,2338,0,512,2331.736,40
193,2695455,IJ-044,SA07337,505,40,0,3,PC,F420/306,26.199,100722,2378,0,515,2357.935,39
194,2695455,IJ-044,SA07337,485,25,0,2,PC,F420/306,17.466,101207,2403,0,517,2375.401,38
195,2695455,IJ-044,SA07337,500,21,0,3,PC,F420/306,26.199,101707,2424,0,520,2401.600,37
196,2695455,IJ-044,SA07337,477,2,0,2,PC,F420/306,17.466,102184,2426,0,522,2419.066,36
197,2695455,IJ-044,SA07337,100,4,0,1,PC,F420/306,8.733,102284,2430,0,523,2427.799,35
198,2695455,IJ-044,SA07337,765,14,0,3,PC,F420/306,26.199,103049,2444,0,526,2453.998,34
199,2695455,IJ-044,SA07337,676,10,0,3,PC,F420/306,26.199,103725,2454,0,529,2480.197,33
200,2695085,IJ-044,SA04416,671,29,0,4,PC,P212/1,23.862,104396,2483,0,533,2504.059,32
201,2695085,IJ-044,SA04416,852,7,0,3,PC,P212/1,15.129,105248,2490,0,536,2519.188,31
202,2695085,IJ-044,SA04416,833,2,0,3,PC,P212/1,15.129,106081,2492,0,539,2534.317,30
203,2695085,IJ-044,SA04416,135,3,0,1,PC,P212/1,5.043,106216,2495,0,540,2539.360,28
204,2695085,IJ-044,SA04416,842,9,0,3,PC,P212/1,15.129,107058,2504,0,543,2554.489,27
205,2695085,IJ-044,SA04416,840,6,0,3,PC,P212/1,15.129,107898,2510,0,546,2569.618,26
206,2695085,IJ-044,SA04416,3,0,0,1,PC,P212/1,5.043,107901,2510,0,547,2574.661,25
207,2695085,IJ-044,SA04416,797,20,0,3,PC,P212/1,15.129,108698,2530,0,550,2589.790,24
208,2695085,IJ-044,SA04416,603,10,0,2,PC,P212/1,10.086,109301,2540,0,552,2599.876,23
209,2695085,IJ-044,SA04416,3,0,0,1,PC,P212/1,5.043,109304,2540,0,553,2604.919,21
210,2695085,IJ-044,SA04416,542,18,0,3,PC,P212/1,15.129,109846,2558,0,556,2620.048,20
211,2695085,IJ-044,SA04416,664,11,0,4,PC,P212/1,23.264,110510,2569,0,560,2643.312,19
212,2695456,IJ-044,SA07339,763,7,0,3,PC,F420/306,19.767,111273,2576,0,563,2663.079,18
213,2695456,IJ-044,SA07339,685,6,0,3,PC,F420/306,19.767,111958,2582,0,566,2682.846,17
214,2697109,IJ-044,SA04416,754,11,0,6,PC,P212/1,34.896,112712,2593,0,572,2717.742,16
215,2697109,IJ-044,SA04416,274,4,0,1,PC,P212/1,5.043,112986,2597,0,573,2722.785,15
216,2697109,IJ-044,SA04416,139,6,0,1,PC,P212/1,5.043,113125,2603,0,574,2727.828,14
217,2697109,IJ-044,SA04416,185,3,0,2,PC,P212/1,10.086,113310,2606,0,576,2737.914,13
218,2697109,IJ-044,SA04416,837,10,0,3,PC,P212/1,15.129,114147,2616,0,579,2753.043,12
219,2697109,IJ-044,SA04416,782,19,0,3,PC,P212/1,15.129,114929,2635,0,582,2768.172,11
220,2697109,IJ-044,SA04416,607,9,0,3,PC,P212/1,15.129,115536,2644,0,585,2783.301,10
221,2697109,IJ-044,SA04416,535,11,0,2,PC,P212/1,10.086,116071,2655,0,587,2793.387,9
222,2697563,IJ-044,SA07371,128,1,0,3,PC,F424/85,21.000,116199,2656,0,590,2814.387,8
223,2697563,IJ-044,SA07371,474,17,0,3,PC,F424/85,21.000,116673,2673,0,593,2835.387,6
224,2697563,IJ-044,SA07371,421,6,0,3,PC,F424/85,21.000,117094,2679,0,596,2856.387,5
225,2697563,IJ-044,SA07371,585,20,0,4,PC,F424/85,28.000,117679,2699,0,600,2884.387,4
226,2697563,IJ-044,SA07371,618,9,0,3,PC,F424/85,21.000,118297,2708,0,603,2905.387,3
227,2697563,IJ-044,SA07371,492,11,0,4,PC,F424/85,28.000,118789,2719,0,607,2933.387,2
228,2697563,IJ-044,SA07371,412,0,0,2,PC,F424/85,14.000,119201,2719,0,609,2947.387,1
229,2697563,IJ-044,SA07371,114,4,0,1,PC,F424/85,7.000,119315,2723,0,610,2954.387,0

In [23]:
df_result.to_csv("mnt-oficial-" + file_, index=False)